"""
Django settings for marches project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os 
from celery.schedules import crontab
from dotenv import load_dotenv
AUTH_USER_MODEL = 'users.PublicProfile'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()
import socket
from urllib.parse import urlsplit, urlunsplit
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    value = os.getenv(name)
    if value is None or value == "":
        return default

    try:
        return int(value)
    except ValueError:
        return default


def env_list(name, default=""):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def _get_lan_ip():
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect(("8.8.8.8", 80))
            return sock.getsockname()[0]
    except OSError:
        return ""


def _resolve_frontend_app_url():
    raw_url = os.getenv("FRONTEND_APP_URL", "http://localhost:3000").rstrip("/")
    parsed = urlsplit(raw_url)

    if DEBUG and parsed.hostname in {"localhost", "127.0.0.1", "0.0.0.0"}:
        lan_host = os.getenv("FRONTEND_LAN_HOST", "").strip() or _get_lan_ip()
        if lan_host:
            port = parsed.port or 3000
            netloc = f"{lan_host}:{port}" if port else lan_host
            return urlunsplit((parsed.scheme or "http", netloc, parsed.path, "", "")).rstrip("/")

    return raw_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

FRONTEND_APP_URL = _resolve_frontend_app_url()
FRONTEND_URL = FRONTEND_APP_URL

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    "192.168.90.167,localhost,127.0.0.1",
)
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
if DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("*")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',

    'corsheaders',#librairie qui autoriser le frontend (Next.js) à appeler API Django.

    'rest_framework',#Django REST Framework permet de creer des APIs
    'rest_framework_simplejwt',#librairie JWT pour l’authentification :login,token,refresh token

    'apps.users',
    'apps.ppm',
    'apps.TdrSt',
    'apps.procurement',
    'apps.log',
    'apps.evaluations',
    'apps.achats',
    'apps.TdrSt',
    'apps.procurement',
    "apps.ouverture_offre",
    'apps.evaluation_offre',
]

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(3, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'marches', 'template', 'marches')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv("DB_ENGINE", 'django.db.backends.postgresql'),
            'NAME': os.getenv("DB_NAME", 'passation_db'),
            'USER': os.getenv("DB_USER", 'postgres'),
            'PASSWORD': os.getenv("DB_PASSWORD", 'passation'),
            'HOST': os.getenv("DB_HOST", 'localhost'),
            'PORT': os.getenv("DB_PORT", '5432'),
            'TEST': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': ':memory:',
            }
            },
            'external_users': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('RH_DB_NAME'),
        'USER': os.environ.get('RH_DB_USER'),
        'PASSWORD': os.environ.get('RH_DB_PASSWORD'),
        'HOST': os.environ.get('RH_DB_HOST'),
        'PORT': os.environ.get('RH_DB_PORT'),
    }
    }
        


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'apps.users.validators.userValidator.ComplexityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Media (uploads) - nécessaire pour servir les PDF téléversés en développement
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

#autoriser acces a front

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-access-type'
]


DEFAULT_FRONTEND_ORIGINS = ",".join([
    FRONTEND_APP_URL,
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
])

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    DEFAULT_FRONTEND_ORIGINS,
)
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    DEFAULT_FRONTEND_ORIGINS,
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'apps.users.authentifications.authentification.HybridJWTAuthentication',
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", DEBUG)

from datetime import timedelta

SIMPLE_JWT = {
    
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # Le token durera 24h
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'SIGNING_KEY': os.environ.get('SECRET_KEY'), 
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTHENTICATION_TOKEN_CLASSES': (
        'rest_framework_simplejwt.authentication.StatelessUserAuthentication',
    ),
}

# Email configuration

# Frontend URL pour les liens
FRONTEND_URL = 'http://localhost:3000'  # À adapter en production

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC' 
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Configuration Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
TIME_ZONE = "Indian/Antananarivo"
CELERY_TIMEZONE = TIME_ZONE
USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@ucp-marches.gov'


CELERY_BEAT_SCHEDULE = {
    "daily-ucp-report": {
        "task": "apps.log.tasks.send_daily_ucp_report_task.send_daily_ucp_report",
        "schedule": crontab(hour=7, minute=0),
    },
    "daily-operational-report": {
        "task": "apps.log.tasks.operational_monitoring_task.send_operational_report",
        "schedule": crontab(hour=7, minute=0),
    },
}
from zoneinfo import available_timezones
print("Indian/Antananarivo" in available_timezones())

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool(
    "EMAIL_USE_TLS",
    EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 10)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@ucp.local")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

ACHATS_NOTIFICATION_EMAILS_ENABLED = env_bool(
    "ACHATS_NOTIFICATION_EMAILS_ENABLED",
    True,
)
ACHATS_EMAIL_SUBJECT_PREFIX = os.getenv(
    "ACHATS_EMAIL_SUBJECT_PREFIX",
    "[UCP Achats] ",
)
ACHATS_NOTIFICATION_REPLY_TO = env_list("ACHATS_NOTIFICATION_REPLY_TO")
TDRST_NOTIFICATION_EMAILS_ENABLED = env_bool(
    "TDRST_NOTIFICATION_EMAILS_ENABLED",
    True,
)
TDRST_EMAIL_SUBJECT_PREFIX = os.getenv(
    "TDRST_EMAIL_SUBJECT_PREFIX",
    "[UCP TDR/ST] ",
)
TDRST_NOTIFICATION_REPLY_TO = env_list("TDRST_NOTIFICATION_REPLY_TO")
OUVERTURE_NOTIFICATION_EMAILS_ENABLED = env_bool(
    "OUVERTURE_NOTIFICATION_EMAILS_ENABLED",
    True,
)
OUVERTURE_EMAIL_SUBJECT_PREFIX = os.getenv(
    "OUVERTURE_EMAIL_SUBJECT_PREFIX",
    "[UCP Ouverture] ",
)
OUVERTURE_NOTIFICATION_REPLY_TO = env_list("OUVERTURE_NOTIFICATION_REPLY_TO")

EXTERNAL_PERSONNEL_API_URL = os.getenv("EXTERNAL_PERSONNEL_API_URL", "")
EXTERNAL_PERSONNEL_API_TOKEN = os.getenv("EXTERNAL_PERSONNEL_API_TOKEN", "")
EXTERNAL_PERSONNEL_API_AUTH_HEADER = os.getenv(
    "EXTERNAL_PERSONNEL_API_AUTH_HEADER",
    "Authorization",
)
EXTERNAL_PERSONNEL_API_AUTH_SCHEME = os.getenv(
    "EXTERNAL_PERSONNEL_API_AUTH_SCHEME",
    "Bearer",
)
EXTERNAL_PERSONNEL_API_TIMEOUT = env_int("EXTERNAL_PERSONNEL_API_TIMEOUT", 15)
