"""
Django settings for marches project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR.parent, '.env'), override=True)

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    value = os.getenv(name)
    if value in [None, ""]:
        return default

    try:
        return int(value)
    except ValueError:
        return default


def env_list(name, default=""):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


FRONTEND_APP_URL = os.getenv("FRONTEND_APP_URL", "http://localhost:3000").rstrip("/")
FRONTEND_URL = FRONTEND_APP_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY") or 'django-insecure-zs0yxq36mps)t8kk85$n=qhf4uyfx5-$7&j(gz(^)ed-@u9$7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    "192.168.90.167,localhost,127.0.0.1",
)
if DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("*")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',#librairie qui autoriser le frontend (Next.js) à appeler API Django.

    'rest_framework',#Django REST Framework permet de creer des APIs
    'rest_framework_simplejwt',#librairie JWT pour l’authentification :login,token,refresh token
    'django_filters',#librairie pour les filtres sur les APIs

    'apps.users',
    'apps.ppm',
    'apps.achats',
    'apps.TdrSt',
    'apps.procurement',
    'apps.ouverture_offre',
    'apps.evaluation_offre',
    'apps.contractualisation',
    'apps.log',
    'apps.contrats',
]

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'marches', 'template', 'marches')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE", 'django.db.backends.postgresql'),
        'NAME': os.getenv("DB_NAME", 'passation_db'),
        'USER': os.getenv("DB_USER", 'postgres'),
        'PASSWORD': os.getenv("DB_PASSWORD", 'passation'),
        'HOST': os.getenv("DB_HOST", 'localhost'),
        'PORT': os.getenv("DB_PORT", '5432'),
        'TEST': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
}
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

#autoriser acces a front

DEFAULT_FRONTEND_ORIGINS = ",".join([
    FRONTEND_APP_URL,
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
])

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    DEFAULT_FRONTEND_ORIGINS,
)
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    DEFAULT_FRONTEND_ORIGINS,
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.users.authentifications.authentification.HybridJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ]
}

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", DEBUG)
CORS_ALLOW_CREDENTIALS = True  # ← Permet les cookies/credentials avec CORS

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-access-type",  # ← Header personnalisé du frontend
    "x-file-type",
    "x-filename",
]

from datetime import timedelta

SIMPLE_JWT = {
    
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # Le token durera 24h
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
MAIL_PROVIDER = os.getenv("MAIL_PROVIDER", "gmail").strip().lower()
PROVIDER_SMTP_DEFAULTS = {
    "gmail": {"host": "smtp.gmail.com", "port": 587, "use_tls": True, "use_ssl": False},
    "brevo": {"host": "smtp-relay.brevo.com", "port": 587, "use_tls": True, "use_ssl": False},
    "mailgun": {"host": "smtp.mailgun.org", "port": 587, "use_tls": True, "use_ssl": False},
    "sendgrid": {"host": "smtp.sendgrid.net", "port": 587, "use_tls": True, "use_ssl": False},
}
provider_defaults = PROVIDER_SMTP_DEFAULTS.get(MAIL_PROVIDER, PROVIDER_SMTP_DEFAULTS["gmail"])
EMAIL_HOST = os.getenv("EMAIL_HOST", provider_defaults["host"])
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", provider_defaults["use_ssl"])
EMAIL_PORT = env_int("EMAIL_PORT", 465 if EMAIL_USE_SSL else provider_defaults["port"])
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool(
    "EMAIL_USE_TLS",
    provider_defaults["use_tls"] and not EMAIL_USE_SSL and EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 30)
DEFAULT_FROM_EMAIL = (
    os.getenv("DEFAULT_FROM_EMAIL")
    or EMAIL_HOST_USER
    or "noreply@ucp.local"
)
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
OUVERTURE_NOTIFICATION_CC = os.getenv("OUVERTURE_NOTIFICATION_CC", "").strip()
OUVERTURE_NOTIFICATION_REPLY_TO = (
    os.getenv("OUVERTURE_NOTIFICATION_REPLY_TO", DEFAULT_FROM_EMAIL) or DEFAULT_FROM_EMAIL
).strip()

CELERY_BROKER_URL = 'redis://localhost:6379/0'
ACHATS_NOTIFICATION_EMAILS_ENABLED = env_bool(
    "ACHATS_NOTIFICATION_EMAILS_ENABLED",
    True,
)
ACHATS_EMAIL_SUBJECT_PREFIX = os.getenv(
    "ACHATS_EMAIL_SUBJECT_PREFIX",
    "[UCP Achats] ",
)
ACHATS_NOTIFICATION_REPLY_TO = env_list("ACHATS_NOTIFICATION_REPLY_TO")
TDRST_NOTIFICATION_EMAILS_ENABLED = env_bool(
    "TDRST_NOTIFICATION_EMAILS_ENABLED",
    True,
)
TDRST_EMAIL_SUBJECT_PREFIX = os.getenv(
    "TDRST_EMAIL_SUBJECT_PREFIX",
    "[UCP TDR/ST] ",
)
TDRST_NOTIFICATION_REPLY_TO = env_list("TDRST_NOTIFICATION_REPLY_TO")

# Ouverture Offre
OUVERTURE_NOTIFICATION_EMAILS_ENABLED = env_bool(
    "OUVERTURE_NOTIFICATION_EMAILS_ENABLED",
    True,
)
OUVERTURE_EMAIL_SUBJECT_PREFIX = os.getenv(
    "OUVERTURE_EMAIL_SUBJECT_PREFIX",
    "[UCP Ouverture] ",
)
OUVERTURE_NOTIFICATION_REPLY_TO = env_list("OUVERTURE_NOTIFICATION_REPLY_TO")

# Evaluation Offre
EVALUATION_NOTIFICATION_EMAILS_ENABLED = env_bool(
    "EVALUATION_NOTIFICATION_EMAILS_ENABLED",
    True,
)
EVALUATION_EMAIL_SUBJECT_PREFIX = os.getenv(
    "EVALUATION_EMAIL_SUBJECT_PREFIX",
    "[UCP Évaluation] ",
)
EVALUATION_NOTIFICATION_REPLY_TO = env_list("EVALUATION_NOTIFICATION_REPLY_TO")
AUTH_USER_MODEL = 'users.UserProfile'

CELERY_BEAT_SCHEDULE = {
    "daily-ucp-report": {
        "task": "apps.log.tasks.send_daily_ucp_report_task.send_daily_ucp_report",
        "schedule": crontab(hour=7, minute=0),
    },
    "daily-operational-report": {
        "task": "apps.log.tasks.operational_monitoring_task.send_operational_report",
        "schedule": crontab(hour=7, minute=0),
    },
}