# Generated by Django 5.2.10 on 2026-06-20 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('procurement', '0008_alter_dateatelier_dates_atelier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CritereTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('ponderation', models.PositiveSmallIntegerField(help_text="Poids en %. La somme des critères actifs d'un AO doit être égale à 100.", validators=[django.core.validators.MaxValueValidator(100)])),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres_techniques', to='procurement.procurementmarket')),
            ],
            options={
                'verbose_name': 'Critère technique',
                'verbose_name_plural': 'Critères techniques',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_elimination_technique', models.PositiveSmallIntegerField(default=70, help_text="Score technique minimum (/100) pour être qualifié à l'ouverture financière.", validators=[django.core.validators.MaxValueValidator(100)])),
                ('poids_technique', models.PositiveSmallIntegerField(default=60)),
                ('poids_financier', models.PositiveSmallIntegerField(default=40)),
                ('seuil_ecart_consensus', models.PositiveSmallIntegerField(default=15, help_text='Écart max toléré entre évaluateur 1 et évaluateur 2 (score technique total) avant consensus requis.')),
                ('nombre_validateurs_requis_double_aveugle', models.PositiveSmallIntegerField(default=3, help_text="Nombre d'évaluateurs devant valider le score technique avant déverrouillage du module financier.")),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_evaluation', to='procurement.procurementmarket')),
            ],
            options={
                'verbose_name': "Configuration d'évaluation",
                'verbose_name_plural': "Configurations d'évaluation",
            },
        ),
        migrations.CreateModel(
            name='EvaluationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'Évaluation en cours'), ('ELIMINE_PRELIMINAIRE', "Éliminé à l'examen préliminaire"), ('ELIMINE_TECHNIQUE', "Éliminé à l'évaluation technique"), ('CONSENSUS_REQUIS', 'Consensus requis entre évaluateurs'), ('QUALIFIE_FINANCIER', 'Qualifié pour ouverture financière'), ('FINALISE', 'Évaluation finalisée')], default='EN_COURS', max_length=30)),
                ('cree_par_external_id', models.CharField(max_length=150)),
                ('cree_par_label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='procurement.procurementmarket')),
            ],
            options={
                'verbose_name': "Évaluation d'offre",
                'verbose_name_plural': "Évaluations d'offres",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_lu', models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Montant lu de l'offre (MGA)")),
                ('corrections_arithmetiques', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18)),
                ('rabais_accordes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18)),
                ('montant_evalue_final', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('montant_moins_disant', models.DecimalField(decimal_places=2, help_text='Montant évalué le plus bas parmi les offres qualifiées du même AO.', max_digits=18)),
                ('score_financier', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('saisi_par_external_id', models.CharField(max_length=150)),
                ('saisi_par_label', models.CharField(blank=True, max_length=255)),
                ('saisi_le', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_financiere', to='evaluations.evaluationheader')),
            ],
            options={
                'verbose_name': 'Évaluation financière',
                'verbose_name_plural': 'Évaluations financières',
            },
        ),
        migrations.CreateModel(
            name='EvaluationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommandation', models.CharField(choices=[('ATTRIBUER', 'Attribuer le marché'), ('REJETER', "Rejeter l'offre"), ('RELANCER', "Relancer l'appel d'offres")], max_length=20)),
                ('justification', models.TextField()),
                ('declaration_absence_conflit_interet', models.BooleanField(help_text="Oui = le comité déclare n'avoir aucun lien avec le soumissionnaire.")),
                ('decide_par_external_id', models.CharField(max_length=150)),
                ('decide_par_label', models.CharField(blank=True, max_length=255)),
                ('decide_le', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='evaluations.evaluationheader')),
            ],
            options={
                'verbose_name': "Décision d'évaluation",
                'verbose_name_plural': "Décisions d'évaluation",
            },
        ),
        migrations.CreateModel(
            name='Evaluateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EVALUATEUR_1', 'Évaluateur 1'), ('EVALUATEUR_2', 'Évaluateur 2'), ('EVALUATEUR_3', 'Évaluateur 3')], max_length=20)),
                ('external_user_id', models.CharField(help_text='Identifiant résolu depuis la base RH via le jeton externe.', max_length=150)),
                ('nom_affiche', models.CharField(max_length=255)),
                ('score_technique_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('a_valide_score_technique', models.BooleanField(default=False, help_text="Confirmation explicite par l'évaluateur — utilisée pour le déverrouillage double-aveugle.")),
                ('a_signe', models.BooleanField(default=False)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('signature_hash', models.CharField(blank=True, help_text='Empreinte de la signature électronique.', max_length=128)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluateurs', to='evaluations.evaluationheader')),
            ],
            options={
                'verbose_name': 'Évaluateur',
                'verbose_name_plural': 'Évaluateurs',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_sur_5', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('note_sur_100', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('note_ponderee', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('commentaire', models.TextField(blank=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='evaluations.criteretechnique')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_techniques', to='evaluations.evaluateur')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_techniques', to='evaluations.evaluationheader')),
            ],
            options={
                'verbose_name': 'Note technique',
                'verbose_name_plural': 'Notes techniques',
            },
        ),
        migrations.CreateModel(
            name='ExamenPreliminaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre_signee_personne_habilitee', models.BooleanField(blank=True, null=True)),
                ('garantie_soumission_conforme', models.BooleanField(blank=True, null=True)),
                ('dossier_administratif_complet', models.BooleanField(blank=True, help_text='NIF, STAT, RCS, Quitus fiscal', null=True)),
                ('validite_offre_conforme', models.BooleanField(blank=True, null=True)),
                ('acceptation_conditions_sans_reserve', models.BooleanField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('evalue_par_external_id', models.CharField(blank=True, max_length=150)),
                ('evalue_par_label', models.CharField(blank=True, max_length=255)),
                ('evalue_le', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_preliminaire', to='evaluations.evaluationheader')),
            ],
            options={
                'verbose_name': 'Examen préliminaire',
                'verbose_name_plural': 'Examens préliminaires',
            },
        ),
        migrations.CreateModel(
            name='ScoreConsolide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_technique', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_financier', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('poids_technique', models.PositiveSmallIntegerField(default=60)),
                ('poids_financier', models.PositiveSmallIntegerField(default=40)),
                ('score_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('rang', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('calcule_le', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_consolide', to='evaluations.evaluationheader')),
            ],
            options={
                'verbose_name': 'Score consolidé',
                'verbose_name_plural': 'Scores consolidés',
                'ordering': ['rang'],
            },
        ),
        migrations.CreateModel(
            name='Soumissionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nif_stat', models.CharField(blank=True, max_length=100, null=True, verbose_name='NIF / STAT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soumissionnaire',
                'verbose_name_plural': 'Soumissionnaires',
                'indexes': [models.Index(fields=['nom'], name='evaluations_nom_c5c128_idx')],
            },
        ),
        migrations.AddField(
            model_name='evaluationheader',
            name='soumissionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.soumissionnaire'),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('external_user_id', models.CharField(max_length=150)),
                ('external_user_label', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "Piste d'audit",
                'verbose_name_plural': "Piste d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='evaluations_content_f4f1e4_idx'), models.Index(fields=['-timestamp'], name='evaluations_timesta_d8c10e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluateur',
            constraint=models.UniqueConstraint(fields=('evaluation', 'role'), name='uniq_role_par_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='evaluationtechnique',
            constraint=models.UniqueConstraint(fields=('evaluation', 'evaluateur', 'critere'), name='uniq_note_par_evaluateur_critere'),
        ),
        migrations.AddConstraint(
            model_name='evaluationheader',
            constraint=models.UniqueConstraint(fields=('marche', 'soumissionnaire', 'lot_numero'), name='uniq_evaluation_par_lot'),
        ),
    ]
