export const PUBLIC = "PUBLIC";
export const DEMANDEUR = "DEMANDEUR";
export const VALIDATEUR_HIERARCHIQUE = "VALIDATEUR_HIERARCHIQUE";
export const VALIDATEUR_TECHNIQUE = "VALIDATEUR_TECHNIQUE";
export const VALIDATEUR_PROGRAMMATIQUE = "VALIDATEUR_PROGRAMMATIQUE";
export const APPROBATEUR_NATIONAL = "APPROBATEUR_NATIONAL";
export const FINANCE = "FINANCE";
export const RAF = "RAF";
export const VALIDATEUR_BUDGETAIRE = "VALIDATEUR_BUDGETAIRE";
export const AGENT_ACHAT = "AGENT_ACHAT";
export const LOGISTIQUE = "LOGISTIQUE";
export const AGENT_MARCHE = "AGENT_MARCHE";
export const MARCHES = "MARCHES";
export const SECRETAIRE = "SECRETAIRE";
export const SECRETAIRE_CONTRACTUALISATION = "SECRETAIRE_CONTRACTUALISATION";
export const AUDITEUR = "AUDITEUR";
export const EVALUATEUR = "EVALUATEUR";
export const PRESIDENT = "PRESIDENT";

export const VALIDATOR_GROUPS = [
  VALIDATEUR_HIERARCHIQUE,
  VALIDATEUR_TECHNIQUE,
  VALIDATEUR_PROGRAMMATIQUE,
  APPROBATEUR_NATIONAL,
] as const;

export const FINANCE_GROUPS = [
  FINANCE,
  RAF,
  VALIDATEUR_BUDGETAIRE,
] as const;

export const MARCHE_GROUPS = [
  LOGISTIQUE,
  AGENT_MARCHE,
  MARCHES,
] as const;
