
PUBLIC = "PUBLIC"
DEMANDEUR = "DEMANDEUR"
VALIDATEUR_HIERARCHIQUE = "VALIDATEUR_HIERARCHIQUE"
VALIDATEUR_TECHNIQUE = "VALIDATEUR_TECHNIQUE"
VALIDATEUR_PROGRAMMATIQUE = "VALIDATEUR_PROGRAMMATIQUE"
APPROBATEUR_NATIONAL = "APPROBATEUR_NATIONAL"
FINANCE = "FINANCE"
RAF = "RAF"
VALIDATEUR_BUDGETAIRE = "VALIDATEUR_BUDGETAIRE"
AGENT_ACHAT = "AGENT_ACHAT"
LOGISTIQUE = "LOGISTIQUE"
AGENT_MARCHE = "AGENT_MARCHE"
MARCHES = "MARCHES"
SECRETAIRE = "SECRETAIRE"
SECRETAIRE_CONTRACTUALISATION = "SECRETAIRE_CONTRACTUALISATION"
AUDITEUR = "AUDITEUR"
EVALUATEUR = "EVALUATEUR"
PRESIDENT = "PRESIDENT"

VALIDATOR_GROUPS = [
    VALIDATEUR_HIERARCHIQUE,
    VALIDATEUR_TECHNIQUE,
    VALIDATEUR_PROGRAMMATIQUE,
    APPROBATEUR_NATIONAL,
]

FINANCE_GROUPS = [
    FINANCE,
    RAF,
    VALIDATEUR_BUDGETAIRE,
]

MARCHE_GROUPS = [
    LOGISTIQUE,
    AGENT_MARCHE,
    MARCHES,
]

ALL_GROUPS = [
    PUBLIC, DEMANDEUR,
    *VALIDATOR_GROUPS,
    *FINANCE_GROUPS,
    AGENT_ACHAT,
    *MARCHE_GROUPS,
    SECRETAIRE, SECRETAIRE_CONTRACTUALISATION,
    AUDITEUR, EVALUATEUR, PRESIDENT,
]
