# Generated by Django 5.2.10 on 2026-07-14 09:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('procedure_type', models.CharField(choices=[('AOI', "Appel d'offres international"), ('AON', "Appel d'offres national"), ('DC', 'Demande de cotation'), ('GRE_A_GRE', 'Gré à gré')], max_length=20)),
                ('category', models.CharField(choices=[('BIENS', 'Biens (matériels et équipements)'), ('SERVICES', 'Services'), ('INFRA', 'Infrastructures (travaux)')], max_length=20)),
                ('financing_sources', models.JSONField(default=list)),
                ('reference_bailleur', models.CharField(blank=True, choices=[('FM', 'Fonds Mondial'), ('GAVI', 'Alliance Gavi'), ('BM', 'Banque Mondiale')], max_length=50, null=True)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('submission_model', models.FileField(blank=True, null=True, upload_to='submission_models/', validators=[django.core.validators.FileExtensionValidator(['docx'])])),
                ('status', models.CharField(choices=[('PUBLISHED', 'Publié'), ('CANCELLED', 'Annulé'), ('CLOSED', 'Clôturé')], default='PUBLISHED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='procurement_created_379d72_idx'), models.Index(fields=['status'], name='procurement_status_6d8b60_idx')],
            },
        ),
        migrations.CreateModel(
            name='DateAtelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_atelier', models.DateTimeField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_previsionnelles', to='procurement.procurementmarket')),
            ],
            options={
                'verbose_name': 'Dates prévisionnelles',
                'ordering': ['dates_atelier'],
            },
        ),
        migrations.CreateModel(
            name='AnnexDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='annex_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexes', to='procurement.procurementmarket')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='technical_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('version', models.PositiveIntegerField(editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_documents', to='procurement.procurementmarket')),
            ],
            options={
                'unique_together': {('market', 'version')},
            },
        ),
    ]
