# Generated by Django 5.2.10 on 2026-05-13 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexdocument',
            name='file',
            field=models.FileField(upload_to='annex_documents/'),
        ),
        migrations.AlterField(
            model_name='technicaldocument',
            name='file',
            field=models.FileField(upload_to='technical_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
