# Generated by Django 5.2.10 on 2026-05-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementmarket',
            old_name='financing_sources',
            new_name='financing_source',
        ),
    ]
