# Generated by Django 5.2.10 on 2026-08-11 11:08

import apps.procurement.models.procurement_market
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementmarket',
            name='category',
            field=models.CharField(choices=apps.procurement.models.procurement_market._category_type_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementmarket',
            name='procedure_type',
            field=models.CharField(choices=apps.procurement.models.procurement_market._procedure_type_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementmarket',
            name='reference_bailleur',
            field=models.CharField(blank=True, choices=apps.procurement.models.procurement_market._financing_source_choices, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procurementmarket',
            name='status',
            field=models.CharField(choices=apps.procurement.models.procurement_market._publication_status_choices, default='PUBLISHED', max_length=20),
        ),
    ]
