# Generated by Django 5.2.10 on 2026-06-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementmarket',
            name='reference_bailleur',
            field=models.CharField(blank=True, choices=[('FM', 'Fonds Mondial'), ('GAVI', 'Alliance Gavi'), ('BM', 'Banque Mondiale')], max_length=50, null=True),
        ),
    ]
