# Generated by Django 5.2.10 on 2026-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_rename_financing_sources_procurementmarket_financing_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldocument',
            name='version',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='technicaldocument',
            unique_together={('market', 'version')},
        ),
    ]
