# Generated by Django 5.2.10 on 2026-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_annexdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementmarket',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
