# Generated by Django 5.2.10 on 2026-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_procurementmarket_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementmarket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='procurementmarket',
            index=models.Index(fields=['-created_at'], name='procurement_created_379d72_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementmarket',
            index=models.Index(fields=['status'], name='procurement_status_6d8b60_idx'),
        ),
    ]
