# Generated by Django 5.2.10 on 2026-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_procurementmarket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementmarket',
            name='date_atelier_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
