# Generated by Django 5.2.10 on 2026-05-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_procurementmarket_date_atelier_prevue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementmarket',
            name='date_atelier_prevue',
        ),
        migrations.CreateModel(
            name='DateAtelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_atelier', models.DateTimeField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_previsionnelles', to='procurement.procurementmarket')),
            ],
            options={
                'verbose_name': 'Dates prévisionnelles',
                'ordering': ['dates_atelier'],
            },
        ),
    ]
