# Generated by Django 5.2.10 on 2026-05-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_remove_procurementmarket_date_atelier_prevue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateatelier',
            name='dates_atelier',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
