# Generated by Django 5.2.10 on 2026-05-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_alter_dateatelier_dates_atelier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateatelier',
            name='dates_atelier',
            field=models.DateTimeField(),
        ),
    ]
