# Generated by Django 5.2.10 on 2026-08-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('PROCEDURE_TYPE', 'Type de procédure'), ('CATEGORY_TYPE', "Catégorie d'achat"), ('PUBLICATION_STATUS', 'Statut de publication'), ('FINANCING_SOURCE', 'Source de financement'), ('CONTRAT_STATUT', 'Statut de contrat'), ('DOCUMENT_TYPE_CONTRAT', 'Type de document contrat')], db_index=True, max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Choix de référence',
                'verbose_name_plural': 'Choix de référence',
                'ordering': ['group', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('group', 'code'), name='unique_group_code')],
            },
        ),
    ]
