# Generated by Django 5.2.10 on 2026-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_seed_extended_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencechoice',
            name='group',
            field=models.CharField(choices=[('PROCEDURE_TYPE', 'Type de procédure'), ('CATEGORY_TYPE', "Catégorie d'achat"), ('PUBLICATION_STATUS', 'Statut de publication'), ('FINANCING_SOURCE', 'Source de financement'), ('CONTRAT_STATUT', 'Statut de contrat'), ('DOCUMENT_TYPE_CONTRAT', 'Type de document contrat'), ('STATUT_PAIEMENT', 'Statut de paiement'), ('ACTION_AUDIT_CONTRAT', 'Action audit contrat'), ('CATEGORIE_BESOIN', 'Catégorie de besoin'), ('TYPE_DEMANDE_ACHAT', "Type de demande d'achat"), ('PRIORITE_ACHAT', "Priorité d'achat"), ('SOURCE_FINANCEMENT_DETAIL', 'Source de financement (détaillée)'), ('STATUT_DEMANDE_ACHAT', "Statut de demande d'achat"), ('ETAPE_VALIDATION_ACHAT', 'Étape de validation achat'), ('TYPE_PROCEDURE_ACHAT', 'Type de procédure achat'), ('ETAT_EXPEDITION', "État d'expédition"), ('CONFORMITE_QUANTITE', 'Conformité quantité'), ('CONFORMITE_QUALITE', 'Conformité qualité'), ('STATUT_RECEPTION', 'Statut de réception'), ('TYPE_ECART', "Type d'écart"), ('ACTION_CORRECTIVE', 'Action corrective'), ('STATUT_FINAL_ACHAT', 'Statut final achat'), ('TYPE_DOCUMENT_ACHAT', 'Type de document achat'), ('ACTION_HISTORIQUE_ACHAT', 'Action historique achat'), ('TYPE_SERVICE_ACHAT', 'Type de service'), ('DECISION_VALIDATION', 'Décision de validation'), ('TYPE_DOCUMENT_TDR_ST', 'Type document TDR/ST'), ('STATUT_TDR_ST', 'Statut TDR/ST'), ('CATEGORIE_ACTIVITE', "Catégorie d'activité"), ('DUREE_UNITE', 'Unité de durée'), ('ETAPE_VALIDATION_TDR_ST', 'Étape validation TDR/ST'), ('DECISION_VALIDATION_TDR_ST', 'Décision validation TDR/ST'), ('STATUT_EVALUATION', "Statut d'évaluation"), ('RECOMMANDATION_EVALUATION', 'Recommandation évaluation'), ('DECLARATION_CONFLIT', 'Déclaration de conflit'), ('STATUT_DAO_EVALUATION', 'Statut DAO évaluation'), ('STATUT_SEANCE', "Statut séance d'ouverture"), ('DECISION_SEANCE', "Décision séance d'ouverture"), ('ETAPE_OUVERTURE', "Étape d'ouverture"), ('ETAT_SCELLE', 'État du scellé'), ('ETAT_ENVELOPPE', "État d'enveloppe"), ('DECISION_MEMBRE_SEANCE', 'Décision membre séance'), ('TYPE_ENTITE', "Type d'entité"), ('SEXE', 'Sexe'), ('TYPE_LOG_DOCUMENT', 'Type de document (log)')], db_index=True, max_length=64),
        ),
    ]
