# Generated by Django 5.2.10 on 2026-05-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeanceOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_dossier', models.CharField(max_length=100)),
                ('objet_dossier', models.CharField(blank=True, max_length=255)),
                ('date_seance', models.DateField(blank=True, null=True)),
                ('heure_seance', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_SAISIE', 'En saisie'), ('A_VALIDER', 'A valider'), ('VALIDEE', 'Validee')], db_index=True, default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_presidees_ouverture', to=settings.AUTH_USER_MODEL)),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances_creees_ouverture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembreSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_present', models.BooleanField(default=True)),
                ('a_valide', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations_ouverture', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='ouverture_offre.seanceouverture')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('seance', 'utilisateur'), name='unique_membre_par_seance')],
            },
        ),
    ]
