# Generated by Django 5.2.10 on 2026-07-08 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeanceOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_dossier', models.CharField(max_length=100)),
                ('objet_dossier', models.CharField(blank=True, max_length=255)),
                ('date_seance', models.DateField(blank=True, null=True)),
                ('heure_seance', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_SAISIE', 'En saisie'), ('EN_VALIDATION_MEMBRES', 'En validation membres'), ('EN_VALIDATION_PRESIDENT', 'En validation president'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee')], db_index=True, default='BROUILLON', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('president_a_valide', models.BooleanField(default=False)),
                ('president_decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee'), ('REPORTEE', 'Reportee')], default='EN_ATTENTE', max_length=20)),
                ('president_commentaire', models.TextField(blank=True)),
                ('date_validation_president', models.DateTimeField(blank=True, null=True)),
                ('president_ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('president_navigateur', models.CharField(blank=True, max_length=255)),
                ('president_validation_password_hash', models.CharField(blank=True, max_length=255)),
                ('president_validation_password_generated_at', models.DateTimeField(blank=True, null=True)),
                ('president_validation_password_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('etape_ouverture', models.CharField(choices=[('COMPLETE', 'Ouverture complete'), ('ADMIN_TECH', 'Ouverture administrative et technique')], default='COMPLETE', max_length=20)),
                ('etat_scelle', models.CharField(blank=True, choices=[('INTACT', 'Intact'), ('ALTERE', 'Altere'), ('ABSENT', 'Absent')], default='', max_length=20)),
                ('presence_rature', models.BooleanField(default=False)),
                ('description_rature', models.TextField(blank=True)),
                ('document_substitution_present', models.BooleanField(default=False)),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_presidees_ouverture', to=settings.AUTH_USER_MODEL)),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances_creees_ouverture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pv_documents/')),
                ('version', models.IntegerField(default=1)),
                ('hash_document', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv_document', to='ouverture_offre.seanceouverture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffreOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_passage', models.PositiveIntegerField()),
                ('nom_soumissionnaire', models.CharField(max_length=255)),
                ('pli_existe', models.BooleanField(default=True)),
                ('motif_absence_pli', models.TextField(blank=True)),
                ('date_reception_pli', models.DateField(blank=True, null=True)),
                ('heure_reception_pli', models.TimeField(blank=True, null=True)),
                ('enveloppe_administrative', models.CharField(blank=True, choices=[('RECU', 'Reçu'), ('INTEGRE', 'Intègre'), ('MANQUANT', 'Manquant'), ('MANQUANTE', 'Manquante'), ('DEPOSEE', 'Déposée')], default='', max_length=20)),
                ('enveloppe_technique', models.CharField(blank=True, choices=[('RECU', 'Reçu'), ('INTEGRE', 'Intègre'), ('MANQUANT', 'Manquant'), ('MANQUANTE', 'Manquante'), ('DEPOSEE', 'Déposée')], default='', max_length=20)),
                ('enveloppe_financiere', models.CharField(blank=True, choices=[('RECU', 'Reçu'), ('INTEGRE', 'Intègre'), ('MANQUANT', 'Manquant'), ('MANQUANTE', 'Manquante'), ('DEPOSEE', 'Déposée')], default='', max_length=20)),
                ('montant_global', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('observations', models.TextField(blank=True)),
                ('lot_numero', models.CharField(blank=True, default='', max_length=100)),
                ('nif_stat', models.CharField(blank=True, default='', max_length=100)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ouverture_offre.seanceouverture')),
            ],
            options={
                'ordering': ['ordre_passage'],
            },
        ),
        migrations.CreateModel(
            name='MembreSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(blank=True, max_length=255)),
                ('numero_carte', models.CharField(blank=True, max_length=50)),
                ('intitule', models.CharField(blank=True, max_length=255)),
                ('poste', models.CharField(blank=True, max_length=255)),
                ('est_present', models.BooleanField(default=True)),
                ('a_valide', models.BooleanField(default=False)),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('navigateur', models.CharField(blank=True, max_length=255)),
                ('validation_password_hash', models.CharField(blank=True, max_length=255)),
                ('validation_password_generated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_password_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations_ouverture', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='ouverture_offre.seanceouverture')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('seance', 'utilisateur'), name='unique_membre_par_seance')],
            },
        ),
    ]
