# Generated by Django 5.2.10 on 2026-06-29 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ouverture_offre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membreseance',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations_ouverture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_presidees_ouverture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances_creees_ouverture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvdocument',
            name='seance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv_document', to='ouverture_offre.seanceouverture'),
        ),
        migrations.AddField(
            model_name='offreouverture',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ouverture_offre.seanceouverture'),
        ),
        migrations.AddField(
            model_name='membreseance',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='ouverture_offre.seanceouverture'),
        ),
        migrations.AddConstraint(
            model_name='membreseance',
            constraint=models.UniqueConstraint(fields=('seance', 'utilisateur'), name='unique_membre_par_seance'),
        ),
    ]
