# Generated by Django 5.2.10 on 2026-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seanceouverture',
            name='date_validation_president',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='president_a_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='president_commentaire',
            field=models.TextField(blank=True),
        ),
    ]
