# Generated by Django 5.2.10 on 2026-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0002_seanceouverture_date_validation_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seanceouverture',
            name='description_rature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='document_substitution_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='etape_ouverture',
            field=models.CharField(choices=[('COMPLETE', 'Ouverture complete'), ('ADMIN_TECH', 'Ouverture administrative et technique')], default='COMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='etat_scelle',
            field=models.CharField(blank=True, choices=[('INTACT', 'Intact'), ('ALTERE', 'Altere'), ('ABSENT', 'Absent')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='presence_rature',
            field=models.BooleanField(default=False),
        ),
    ]
