# Generated by Django 5.2.10 on 2026-08-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seanceouverture',
            name='category_type',
            field=models.CharField(blank=True, choices=[('BIENS', 'Biens (matériels et équipements)'), ('SERVICES', 'Services'), ('INFRA', 'Infrastructures (travaux)')], db_index=True, default='', help_text="Catégorie d'achat du dossier (BIENS / SERVICES / INFRA). Résolu automatiquement ou saisi manuellement.", max_length=20),
        ),
    ]
