# Generated by Django 5.2.10 on 2026-08-25 11:23

import apps.ouverture_offre.models.membre_seance
import apps.ouverture_offre.models.offre_ouverture
import apps.ouverture_offre.models.seance_ouverture
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0003_seanceouverture_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreseance',
            name='decision',
            field=models.CharField(choices=apps.ouverture_offre.models.membre_seance._decision_membre_seance_choices, default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='offreouverture',
            name='enveloppe_administrative',
            field=models.CharField(blank=True, choices=apps.ouverture_offre.models.offre_ouverture._etat_enveloppe_choices, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='offreouverture',
            name='enveloppe_financiere',
            field=models.CharField(blank=True, choices=apps.ouverture_offre.models.offre_ouverture._etat_enveloppe_choices, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='offreouverture',
            name='enveloppe_technique',
            field=models.CharField(blank=True, choices=apps.ouverture_offre.models.offre_ouverture._etat_enveloppe_choices, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seanceouverture',
            name='category_type',
            field=models.CharField(blank=True, choices=apps.ouverture_offre.models.seance_ouverture._category_type_choices, db_index=True, default='', help_text="Catégorie d'achat du dossier (BIENS / SERVICES / INFRA). Résolu automatiquement ou saisi manuellement.", max_length=20),
        ),
        migrations.AlterField(
            model_name='seanceouverture',
            name='etape_ouverture',
            field=models.CharField(choices=apps.ouverture_offre.models.seance_ouverture._etape_ouverture_choices, default='COMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='seanceouverture',
            name='etat_scelle',
            field=models.CharField(blank=True, choices=apps.ouverture_offre.models.seance_ouverture._etat_scelle_choices, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seanceouverture',
            name='president_decision',
            field=models.CharField(choices=apps.ouverture_offre.models.seance_ouverture._decision_seance_choices, default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='seanceouverture',
            name='statut',
            field=models.CharField(choices=apps.ouverture_offre.models.seance_ouverture._statut_seance_choices, db_index=True, default='BROUILLON', max_length=32),
        ),
    ]
