# Generated by Django 5.2.10 on 2026-05-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0003_seanceouverture_description_rature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_passage', models.PositiveIntegerField()),
                ('nom_soumissionnaire', models.CharField(max_length=255)),
                ('pli_existe', models.BooleanField(default=True)),
                ('motif_absence_pli', models.TextField(blank=True)),
                ('date_reception_pli', models.DateField(blank=True, null=True)),
                ('heure_reception_pli', models.TimeField(blank=True, null=True)),
                ('enveloppe_administrative', models.CharField(blank=True, choices=[('DEPOSEE', 'Deposee'), ('MANQUANTE', 'Manquante')], default='', max_length=20)),
                ('enveloppe_technique', models.CharField(blank=True, choices=[('DEPOSEE', 'Deposee'), ('MANQUANTE', 'Manquante')], default='', max_length=20)),
                ('enveloppe_financiere', models.CharField(blank=True, choices=[('DEPOSEE', 'Deposee'), ('MANQUANTE', 'Manquante')], default='', max_length=20)),
                ('montant_global', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('observations', models.TextField(blank=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ouverture_offre.seanceouverture')),
            ],
            options={
                'ordering': ['ordre_passage'],
            },
        ),
    ]
