# Generated by Django 5.2.10 on 2026-05-20 08:59

from django.db import migrations, models


def backfill_validation_decisions(apps, schema_editor):
    MembreSeance = apps.get_model("ouverture_offre", "MembreSeance")
    SeanceOuverture = apps.get_model("ouverture_offre", "SeanceOuverture")

    MembreSeance.objects.filter(a_valide=True).update(decision="VALIDEE")
    SeanceOuverture.objects.filter(president_a_valide=True).update(
        president_decision="VALIDEE"
    )
    SeanceOuverture.objects.filter(
        statut="VALIDEE",
        president_decision="EN_ATTENTE",
    ).update(president_decision="VALIDEE")


def reset_validation_decisions(apps, schema_editor):
    MembreSeance = apps.get_model("ouverture_offre", "MembreSeance")
    SeanceOuverture = apps.get_model("ouverture_offre", "SeanceOuverture")

    MembreSeance.objects.filter(decision="VALIDEE").update(decision="EN_ATTENTE")
    SeanceOuverture.objects.filter(president_decision="VALIDEE").update(
        president_decision="EN_ATTENTE"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0004_offreouverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreseance',
            name='decision',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='president_decision',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='seanceouverture',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_SAISIE', 'En saisie'), ('A_VALIDER', 'A valider'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee')], db_index=True, default='BROUILLON', max_length=20),
        ),
        migrations.RunPython(
            backfill_validation_decisions,
            reset_validation_decisions,
        ),
    ]
