# Generated by Django 5.2.10 on 2026-07-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0004_validationcompositionmembre_notification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreouverture',
            name='nif',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offreouverture',
            name='stat',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='validationcompositionmembre',
            name='role',
            field=models.CharField(choices=[('CN', 'Coordonnateur National'), ('GP', 'Gestionnaire de Programme'), ('RPM', 'Responsable Passation de Marché')], max_length=8),
        ),
    ]
