# Generated by Django 5.2.10 on 2026-05-22 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0006_split_validation_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreseance',
            name='ip_adresse',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membreseance',
            name='navigateur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='president_ip_adresse',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seanceouverture',
            name='president_navigateur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pv_documents/')),
                ('version', models.IntegerField(default=1)),
                ('hash_document', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv_document', to='ouverture_offre.seanceouverture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
