# Generated by Django 5.2.10 on 2026-05-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0007_membreseance_ip_adresse_membreseance_navigateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreouverture',
            name='enveloppe_administrative',
            field=models.CharField(blank=True, choices=[('RECU', 'Reçu'), ('INTEGRE', 'Intègre'), ('MANQUANT', 'Manquant'), ('MANQUANTE', 'Manquante'), ('DEPOSEE', 'Déposée')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='offreouverture',
            name='enveloppe_financiere',
            field=models.CharField(blank=True, choices=[('RECU', 'Reçu'), ('INTEGRE', 'Intègre'), ('MANQUANT', 'Manquant'), ('MANQUANTE', 'Manquante'), ('DEPOSEE', 'Déposée')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='offreouverture',
            name='enveloppe_technique',
            field=models.CharField(blank=True, choices=[('RECU', 'Reçu'), ('INTEGRE', 'Intègre'), ('MANQUANT', 'Manquant'), ('MANQUANTE', 'Manquante'), ('DEPOSEE', 'Déposée')], default='', max_length=20),
        ),
    ]
