# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouverture_offre", "0008_alter_offreouverture_enveloppe_administrative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membreseance",
            name="validation_password_consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membreseance",
            name="validation_password_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membreseance",
            name="validation_password_hash",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="seanceouverture",
            name="president_validation_password_consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seanceouverture",
            name="president_validation_password_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seanceouverture",
            name="president_validation_password_hash",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="seanceouverture",
            name="president_decision",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("VALIDEE", "Validee"),
                    ("REJETEE", "Rejetee"),
                    ("REPORTEE", "Reportee"),
                ],
                default="EN_ATTENTE",
                max_length=20,
            ),
        ),
    ]
