# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouverture_offre", "0009_validation_passwords_and_reported_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="membreseance",
            name="nom_prenom",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="membreseance",
            name="numero_carte",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="membreseance",
            name="intitule",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="membreseance",
            name="poste",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
