# Generated by Codex on 2026-06-01

from django.db import migrations, models


def move_archived_to_validated(apps, schema_editor):
    SeanceOuverture = apps.get_model("ouverture_offre", "SeanceOuverture")
    SeanceOuverture.objects.filter(statut="ARCHIVEE").update(statut="VALIDEE")


class Migration(migrations.Migration):

    dependencies = [
        ("ouverture_offre", "0010_membreseance_identite_commission"),
    ]

    operations = [
        migrations.RunPython(move_archived_to_validated, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="seanceouverture",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("EN_SAISIE", "En saisie"),
                    ("EN_VALIDATION_MEMBRES", "En validation membres"),
                    ("EN_VALIDATION_PRESIDENT", "En validation president"),
                    ("VALIDEE", "Validee"),
                    ("REJETEE", "Rejetee"),
                ],
                db_index=True,
                default="BROUILLON",
                max_length=32,
            ),
        ),
    ]
