# Generated by Django 5.2.10 on 2026-06-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouverture_offre', '0011_remove_archived_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreouverture',
            name='lot_numero',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offreouverture',
            name='nif_stat',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
