# Generated by Django 5.2.10 on 2026-07-08 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du Programme/Financement')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Programme (ex: GAVI, FM)')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Intitulé du Poste')),
                ('groups', models.ManyToManyField(blank=True, related_name='postes', to='auth.group', verbose_name='Groupes Django (Permissions)')),
                ('superieurs', models.ManyToManyField(blank=True, related_name='subordonnes', to='users.poste', verbose_name='Supérieurs hiérarchiques')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='users.programme', verbose_name='Programme rattaché')),
            ],
            options={
                'unique_together': {('nom', 'programme')},
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sexe', models.IntegerField(blank=True, choices=[(1, 'Masculin'), (2, 'Féminin')], null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='users.poste')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email professionnel')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Le format doit être : +261 XX XXX XX', regex='^\\+261\\s\\d{2}\\s\\d{3}\\s\\d{2}$')])),
                ('type_entite', models.CharField(blank=True, choices=[('ENTREPRISE', 'Entreprise'), ('BUREAU_ETUDES', 'Bureau d’études'), ('ONG', 'ONG'), ('PARTICULIER', 'Particulier'), ('CONSULTANT', 'Consultant')], max_length=20, null=True)),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', null=True, related_name='userprofile_group', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', null=True, related_name='userprofile_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
