<<<<<<< HEAD
# Generated by Django 5.2.10 on 2026-04-27 09:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
=======
# Generated manually to introduce a profile/role linked to Django's User model.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 7b486334ce89722f0fe5f9ac46339b85f31f2c7d
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email professionnel')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Le format doit être : +261 XX XXX XX', regex='^\\+261\\s\\d{2}\\s\\d{3}\\s\\d{2}$')])),
                ('type_entite', models.CharField(choices=[('ENTREPRISE', 'Entreprise'), ('BUREAU_ETUDES', 'Bureau d’études'), ('ONG', 'ONG'), ('PARTICULIER', 'Particulier'), ('CONSULTANT', 'Consultant')], max_length=20)),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('initiateur', 'Initiateur'), ('verificateur_technique', 'Vérificateur technique'), ('approbateur_final', 'Approbateur final'), ('bailleur', 'Bailleur'), ('auditeur', 'Auditeur')], db_index=True, default='initiateur', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
=======
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("demandeur", "Demandeur"),
                            ("verificateur_technique", "Vérificateur technique"),
                            ("approbateur_final", "Approbateur final"),
                            ("bailleur", "Bailleur"),
                        ],
                        db_index=True,
                        default="demandeur",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> 7b486334ce89722f0fe5f9ac46339b85f31f2c7d
            ],
        ),
    ]
