# Generated by Django 5.2.10 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('initiateur', 'Initiateur'), ('verificateur_technique', 'Vérificateur technique'), ('approbateur_final', 'Approbateur final'), ('bailleur', 'Bailleur'), ('auditeur', 'Auditeur')], db_index=True, default='initiateur', max_length=32),
        ),
    ]
