# Generated by Django 5.2.10 on 2026-06-30 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_publicprofile_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du Programme/Financement')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Programme (ex: GAVI, FM)')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Intitulé du Poste')),
                ('groups', models.ManyToManyField(blank=True, related_name='postes', to='auth.group', verbose_name='Groupes Django (Permissions)')),
                ('superieurs', models.ManyToManyField(blank=True, related_name='subordonnes', to='users.poste', verbose_name='Supérieurs hiérarchiques')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='users.programme', verbose_name='Programme rattaché')),
            ],
            options={
                'unique_together': {('nom', 'programme')},
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sexe', models.IntegerField(blank=True, choices=[(1, 'Masculin'), (2, 'Féminin')], null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='users.poste')),
            ],
        ),
    ]
