# Generated by Django 5.2.10 on 2026-08-25 11:23

import apps.users.models.agent
import apps.users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='sexe',
            field=models.IntegerField(blank=True, choices=apps.users.models.agent._sexe_choices, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type_entite',
            field=models.CharField(blank=True, choices=apps.users.models.user._type_entite_choices, max_length=20, null=True),
        ),
    ]
