# Generated by Django 5.2.10 on 2026-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('demandeur', 'Demandeur'), ('verificateur_technique', 'Vérificateur technique'), ('approbateur_final', 'Approbateur final'), ('auditeur', 'Auditeur')], db_index=True, default='demandeur', max_length=32),
        ),
    ]
