# Generated by Django 5.2.10 on 2026-07-07 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_marche', models.CharField(max_length=100, unique=True)),
                ('projet', models.CharField(blank=True, max_length=100, null=True)),
                ('prestataire_id', models.BigIntegerField(db_index=True)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_signature', models.DateField()),
                ('duree_execution', models.DurationField()),
                ('clauses_particulieres', models.TextField(blank=True)),
                ('echeancier', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ATTENTE_SIGNATURE', 'En attente de signature'), ('EXECUTION', 'En exécution'), ('TERMINE', 'Terminé')], default='BROUILLON', max_length=30)),
                ('representant_signataire', models.CharField(blank=True, max_length=255)),
                ('fonction_signataire', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contrats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ContratAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.BigIntegerField(db_index=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contrats.contrat')),
            ],
            options={
                'db_table': 'contrat_audit_log',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CONTRAT_SIGNE', 'Contrat signé'), ('AVENANT', 'Avenant')], max_length=30)),
                ('fichier', models.FileField(upload_to='contrats/')),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contrats.contrat')),
            ],
            options={
                'db_table': 'documents_contrat',
            },
        ),
        migrations.CreateModel(
            name='EcheancePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('condition', models.TextField(blank=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='contrats.contrat')),
            ],
            options={
                'db_table': 'contrat_echeances',
                'ordering': ['ordre'],
            },
        ),
    ]
