# Generated by Django 5.2.10 on 2026-08-11 11:08

import apps.contrats.models.contrats
import apps.contrats.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=apps.contrats.models.contrats._contrat_statut_choices, default='BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentcontrat',
            name='type_document',
            field=models.CharField(choices=apps.contrats.models.document._type_document_choices, max_length=30),
        ),
    ]
