# Generated by Django 5.2.10 on 2026-03-05 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(blank=True, help_text='[Généré automatiquement] Format suggéré: UCP/DA/[Année]/[Séquentiel]', max_length=50, null=True, unique=True, verbose_name='Numéro de la Demande')),
                ('date_demande', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la Demande')),
                ('service_demandeur', models.CharField(max_length=100)),
                ('demandeur_nom', models.CharField(max_length=150)),
                ('fonction_demandeur', models.CharField(max_length=100)),
                ('activite_ptba', models.CharField(help_text='Activité et Sous-activité (ex: Activité > Sous-activité)', max_length=200)),
                ('indicateur_performance', models.CharField(blank=True, max_length=200, null=True)),
                ('source_financement', models.CharField(choices=[('FONDS_MONDIAL', 'Fonds Mondial'), ('GAVI', 'Gavi'), ('BANQUE_MONDIALE', 'Banque mondiale'), ('BUDGET_ETAT', 'Budget Etat (Contrepartie)'), ('AUTRE', 'Autre')], max_length=50)),
                ('precision_financement', models.CharField(blank=True, help_text='Ex: Subvention VIH Round 10', max_length=200, null=True)),
                ('ligne_budgetaire', models.CharField(help_text='Ex: FM-PAL-2024-02', max_length=100)),
                ('budget_estime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('FCFA', 'FCFA')], default='USD', max_length=10)),
                ('type_marche', models.CharField(choices=[('BIENS', 'Biens (Fournitures, équipements...)'), ('SERVICES', 'Services (Prestations intellectuelles...)'), ('TRAVAUX', 'Travaux / Infrastructures')], max_length=20)),
                ('nature_activite', models.CharField(choices=[('FORMATION', 'Formation / Atelier'), ('REUNION', 'Réunion / Séminaire'), ('SUPERVISION', 'Mission de supervision / Suivi-évaluation'), ('REVUE', 'Revue (annuelle, données)'), ('CONSTRUCTION', 'Construction / Réhabilitation'), ('AUTRE', 'Autre')], max_length=20)),
                ('precision_nature_activite', models.CharField(blank=True, max_length=200, null=True)),
                ('intitule_demande', models.CharField(max_length=255)),
                ('description_detaillee', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='demandes_achats/pieces_jointes/')),
                ('lieu_livraison_region', models.CharField(max_length=100)),
                ('lieu_livraison_adresse', models.TextField()),
                ('date_debut_souhaitee', models.DateField()),
                ('date_fin_souhaitee', models.DateField()),
                ('est_urgent', models.BooleanField(default=False)),
                ('justification_urgence', models.TextField(blank=True, null=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE_BUDGET', 'Validée Budget'), ('VALIDEE_DIRECTION', 'Validée Direction'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=20, verbose_name='Statut de la Demande')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
