# Generated by Django 5.2.10 on 2026-03-08 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='date_demande',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de la Demande'),
        ),
    ]
