# Generated by Django 5.2.10 on 2026-03-09 08:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_alter_demandeachat_date_demande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeachat',
            old_name='lieu_livraison_adresse',
            new_name='adresse_precise',
        ),
        migrations.RenameField(
            model_name='demandeachat',
            old_name='demandeur_nom',
            new_name='nom_demandeur',
        ),
        migrations.RenameField(
            model_name='demandeachat',
            old_name='lieu_livraison_region',
            new_name='region_district',
        ),
        migrations.RenameField(
            model_name='demandeachat',
            old_name='est_urgent',
            new_name='urgent',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='precision_financement',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='precision_nature_activite',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='titre',
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_transmission_marches',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='nature_activite_autre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='source_financement_autre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='source_financement_projet_bm',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='source_financement_subvention_fm',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='sous_activite_ptba',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur1_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur1_decision',
            field=models.CharField(blank=True, choices=[('', ''), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté')], max_length=20),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur1_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur2_fonds',
            field=models.CharField(blank=True, choices=[('', ''), ('Fonds disponibles', 'Fonds disponibles'), ('Fonds insuffisants', 'Fonds insuffisants')], max_length=30),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur2_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur2_visa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur3_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='validateur3_visa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='activite_ptba',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='date_demande',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='indicateur_performance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='justification_urgence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='ligne_budgetaire',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='nature_activite',
            field=models.CharField(blank=True, choices=[('Formation / Atelier', 'Formation / Atelier'), ('Réunion / Séminaire', 'Réunion / Séminaire'), ('Mission de supervision / Suivi-évaluation', 'Mission de supervision / Suivi-évaluation'), ('Revue', 'Revue'), ('Construction / Réhabilitation', 'Construction / Réhabilitation'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='numero_demande',
            field=models.CharField(blank=True, help_text='Genere automatiquement au format UCP/DA/ANNEE/SEQUENCE.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='source_financement',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Soumise', 'Soumise'), ('Validée Budget', 'Validée Budget'), ('Validée Direction', 'Validée Direction'), ('Rejetée', 'Rejetée'), ('Transmise aux Marchés', 'Transmise aux Marchés')], default='Brouillon', max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='type_marche',
            field=models.CharField(choices=[('Biens', 'Biens'), ('Services', 'Services'), ('Travaux', 'Travaux')], max_length=20),
        ),
    ]
