# Generated by Django 5.2.10 on 2026-03-26 18:41

import apps.TdrSt.models.TdrSt
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TdrStDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_document', models.CharField(blank=True, db_index=True, max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unite_technique', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu')], db_index=True, default='BROUILLON', max_length=20)),
                ('type_document', models.CharField(choices=[('TDR', 'Termes de Référence (TDR)'), ('ST', 'Spécifications Techniques (ST)')], max_length=3)),
                ('categorie_activite', models.CharField(choices=[('FORMATION', 'Formation'), ('ATELIER', 'Atelier'), ('REUNION', 'Réunion'), ('REVUE', 'Revue'), ('SUPERVISION', 'Supervision'), ('ETUDE', 'Étude'), ('CONSULTANT', 'Consultant'), ('CABINET', 'Cabinet'), ('BUREAU_ETUDES', "Bureau d'études"), ('ENTREPRISE', 'Entreprise'), ('BIENS', 'Biens'), ('INFRASTRUCTURE', 'Infrastructure')], max_length=32)),
                ('intitule', models.CharField(max_length=255)),
                ('reference_ptba', models.CharField(max_length=100)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('duree_estimee_valeur', models.PositiveIntegerField()),
                ('duree_estimee_unite', models.CharField(choices=[('JOURS', 'Jours'), ('MOIS', 'Mois')], max_length=8)),
                ('sources_financement', models.JSONField(default=list)),
                ('numero_subvention', models.CharField(blank=True, max_length=100)),
                ('ligne_budgetaire', models.CharField(max_length=100)),
                ('montant_estime_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('seuil_passation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('procedure_envisagee', models.CharField(choices=[('DC', 'DC'), ('AOI', 'AOI'), ('AON', 'AON'), ('GRE_A_GRE', 'Gré à gré')], max_length=20)),
                ('demandeur', models.ForeignKey(db_column='initiateur_id', on_delete=django.db.models.deletion.PROTECT, related_name='tdr_st_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tdr_st_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TdrStDocumentFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('fichier_pdf', models.FileField(upload_to=apps.TdrSt.models.TdrSt._upload_to)),
                ('fichier_nom_original', models.CharField(blank=True, max_length=255)),
                ('fichier_taille_octets', models.BigIntegerField(blank=True, null=True)),
                ('empreinte_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_fichier', to='TdrSt.tdrstdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tdr_st_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tdr_st_document_file_version',
                'ordering': ['-version'],
                'unique_together': {('document', 'version')},
            },
        ),
        migrations.AddField(
            model_name='tdrstdocument',
            name='fichier_courant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='TdrSt.tdrstdocumentfileversion'),
        ),
        migrations.CreateModel(
            name='TdrStValidationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('DEPOT', 'Dépôt'), ('VALIDATION_TECHNIQUE', 'Validation technique'), ('APPROBATION_FINALE', 'Approbation finale')], max_length=32)),
                ('decision', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable'), ('A_REVOIR', 'À revoir'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu')], max_length=16)),
                ('observations', models.TextField(blank=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tdr_st_validation_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_validation', to='TdrSt.tdrstdocument')),
            ],
            options={
                'db_table': 'tdr_st_validation_action',
                'ordering': ['-horodatage'],
            },
        ),
    ]
