# Generated by Django 5.2.10 on 2026-07-14 09:14

import apps.TdrSt.models.TdrSt
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TdrStDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_document', models.CharField(blank=True, db_index=True, max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unite_technique', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_VALIDATION', 'En validation'), ('A_REVOIR', 'à revoir'), ('EN_ATTENTE_ANO', 'En attente ANO'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu')], db_index=True, default='BROUILLON', max_length=20)),
                ('type_document', models.CharField(choices=[('TDR', 'Termes de Référence (TDR)'), ('ST', 'Spécifications Techniques (ST)')], max_length=3)),
                ('categorie_activite', models.CharField(choices=[('FORMATION', 'Formation'), ('ATELIER', 'Atelier'), ('REUNION', 'Réunion'), ('REVUE', 'Revue'), ('SUPERVISION', 'Supervision'), ('ETUDE', 'Etude'), ('CONSULTANT', 'Consultant'), ('CABINET', 'Cabinet'), ('BUREAU_ETUDES', "Bureau d'Ã©tudes"), ('ENTREPRISE', 'Entreprise'), ('BIENS', 'Biens'), ('INFRASTRUCTURE', 'Infrastructure')], max_length=32)),
                ('intitule', models.CharField(max_length=255)),
                ('reference_ptba', models.CharField(max_length=100)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('duree_estimee_valeur', models.PositiveIntegerField()),
                ('duree_estimee_unite', models.CharField(choices=[('JOURS', 'Jours'), ('MOIS', 'Mois')], max_length=8)),
                ('sources_financement', models.JSONField(default=list)),
                ('numero_subvention', models.CharField(blank=True, max_length=100)),
                ('ligne_budgetaire', models.CharField(blank=True, max_length=100)),
                ('montant_estime_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('seuil_passation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('procedure_envisagee', models.CharField(choices=[('DC', 'DC'), ('AOI', 'AOI'), ('AON', 'AON'), ('GRE_A_GRE', 'Gré à gré')], max_length=20)),
            ],
            options={
                'db_table': 'tdr_st_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TdrStDocumentFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('fichier_pdf', models.FileField(upload_to=apps.TdrSt.models.TdrSt._upload_to)),
                ('fichier_nom_original', models.CharField(blank=True, max_length=255)),
                ('fichier_taille_octets', models.BigIntegerField(blank=True, null=True)),
                ('empreinte_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tdr_st_document_file_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TdrStValidationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('DEPOT', 'Dépôt'), ('VALIDATION_TECHNIQUE', 'Validation technique'), ('APPROBATION_FINALE', 'Approbation finale'), ('ANO', 'Avis de Non-Objection (ANO)'), ('SUSPENSION', 'Suspension')], max_length=32)),
                ('decision', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('A_REVOIR', 'À revoir'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu'), ('ANO_ACCORDE', 'ANO accordé'), ('ANO_REFUSE', 'ANO refusé')], max_length=16)),
                ('observations', models.TextField(blank=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tdr_st_validation_action',
                'ordering': ['-horodatage'],
            },
        ),
    ]
