# Generated by Django 5.2.10 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TdrSt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdrstdocument',
            name='categorie_activite',
            field=models.CharField(choices=[('FORMATION', 'Formation'), ('ATELIER', 'Atelier'), ('REUNION', 'RÃ©union'), ('REVUE', 'Revue'), ('SUPERVISION', 'Supervision'), ('ETUDE', 'Ã‰tude'), ('CONSULTANT', 'Consultant'), ('CABINET', 'Cabinet'), ('BUREAU_ETUDES', "Bureau d'Ã©tudes"), ('ENTREPRISE', 'Entreprise'), ('BIENS', 'Biens'), ('INFRASTRUCTURE', 'Infrastructure')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='procedure_envisagee',
            field=models.CharField(choices=[('DC', 'DC'), ('AOI', 'AOI'), ('AON', 'AON'), ('GRE_A_GRE', 'GrÃ© Ã\xa0 grÃ©')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_VALIDATION', 'En validation'), ('A_REVOIR', 'Ã€ revoir'), ('EN_ATTENTE_ANO', 'En attente ANO'), ('VALIDE', 'ValidÃ©'), ('REJETE', 'RejetÃ©'), ('SUSPENDU', 'Suspendu')], db_index=True, default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='type_document',
            field=models.CharField(choices=[('TDR', 'Termes de RÃ©fÃ©rence (TDR)'), ('ST', 'SpÃ©cifications Techniques (ST)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tdrstvalidationaction',
            name='decision',
            field=models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('A_REVOIR', 'À revoir'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu'), ('ANO_ACCORDE', 'ANO accordé'), ('ANO_REFUSE', 'ANO refusé')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tdrstvalidationaction',
            name='etape',
            field=models.CharField(choices=[('DEPOT', 'Dépôt'), ('VALIDATION_TECHNIQUE', 'Validation technique'), ('APPROBATION_FINALE', 'Approbation finale'), ('ANO', 'Avis de Non-Objection (ANO)'), ('SUSPENSION', 'Suspension')], max_length=32),
        ),
    ]
