# Generated by Django 5.2.10 on 2026-06-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TdrSt', '0001_initial'),
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdrstdocument',
            name='demande_achat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdr_st_document', to='achats.demandeachat'),
        ),
    ]
