# Generated by Django 5.2.10 on 2026-07-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TdrSt', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tdrstdocument',
            name='demandeur',
            field=models.ForeignKey(db_column='demandeur_id', on_delete=django.db.models.deletion.PROTECT, related_name='tdr_st_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdrstdocumentfileversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_fichier', to='TdrSt.tdrstdocument'),
        ),
        migrations.AddField(
            model_name='tdrstdocumentfileversion',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tdr_st_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdrstdocument',
            name='fichier_courant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='TdrSt.tdrstdocumentfileversion'),
        ),
        migrations.AddField(
            model_name='tdrstvalidationaction',
            name='acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tdr_st_validation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdrstvalidationaction',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_validation', to='TdrSt.tdrstdocument'),
        ),
        migrations.AlterUniqueTogether(
            name='tdrstdocumentfileversion',
            unique_together={('document', 'version')},
        ),
    ]
