# Generated by Django 5.2.10 on 2026-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TdrSt', '0002_alter_tdrstdocument_categorie_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdrstdocument',
            name='categorie_activite',
            field=models.CharField(choices=[('FORMATION', 'Formation'), ('ATELIER', 'Atelier'), ('REUNION', 'Réunion'), ('REVUE', 'Revue'), ('SUPERVISION', 'Supervision'), ('ETUDE', 'Etude'), ('CONSULTANT', 'Consultant'), ('CABINET', 'Cabinet'), ('BUREAU_ETUDES', "Bureau d'Ã©tudes"), ('ENTREPRISE', 'Entreprise'), ('BIENS', 'Biens'), ('INFRASTRUCTURE', 'Infrastructure')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='procedure_envisagee',
            field=models.CharField(choices=[('DC', 'DC'), ('AOI', 'AOI'), ('AON', 'AON'), ('GRE_A_GRE', 'Gré à gré')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_VALIDATION', 'En validation'), ('A_REVOIR', 'à revoir'), ('EN_ATTENTE_ANO', 'En attente ANO'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu')], db_index=True, default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='type_document',
            field=models.CharField(choices=[('TDR', 'Termes de Référence (TDR)'), ('ST', 'Spécifications Techniques (ST)')], max_length=3),
        ),
    ]
