# Generated by Django 5.2.10 on 2026-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TdrSt', '0003_alter_tdrstdocument_categorie_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdrstdocumentfileversion',
            name='snapshot_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
