# Generated by Django 5.2.10 on 2026-08-11 11:08

import apps.TdrSt.models.TdrSt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TdrSt', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdrstdocument',
            name='procedure_envisagee',
            field=models.CharField(choices=apps.TdrSt.models.TdrSt._procedure_envisagee_choices, max_length=20),
        ),
    ]
