# Generated by Django 5.2.10 on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0002_initial"),
        ("TdrSt", "0004_tdrstdocumentfileversion_snapshot_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tdrstdocument",
            name="demande_achat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tdr_st_document",
                to="achats.demandeachat",
            ),
        ),
        migrations.AlterField(
            model_name="tdrstdocument",
            name="ligne_budgetaire",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
