# Generated by Django 5.2.10 on 2026-08-25 11:23

import apps.TdrSt.models.TdrSt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TdrSt', '0004_alter_tdrstdocument_procedure_envisagee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdrstdocument',
            name='categorie_activite',
            field=models.CharField(choices=apps.TdrSt.models.TdrSt._categorie_activite_choices, max_length=32),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='duree_estimee_unite',
            field=models.CharField(choices=apps.TdrSt.models.TdrSt._duree_unite_choices, max_length=8),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='statut',
            field=models.CharField(choices=apps.TdrSt.models.TdrSt._statut_tdr_st_choices, db_index=True, default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='tdrstdocument',
            name='type_document',
            field=models.CharField(choices=apps.TdrSt.models.TdrSt._type_document_tdr_st_choices, max_length=3),
        ),
        migrations.AlterField(
            model_name='tdrstvalidationaction',
            name='decision',
            field=models.CharField(blank=True, choices=apps.TdrSt.models.TdrSt._decision_validation_tdr_st_choices, max_length=16),
        ),
        migrations.AlterField(
            model_name='tdrstvalidationaction',
            name='etape',
            field=models.CharField(choices=apps.TdrSt.models.TdrSt._etape_validation_tdr_st_choices, max_length=32),
        ),
    ]
