# Generated by Django 5.2.10 on 2026-06-30 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TdrSt', '0005_tdrstdocument_demande_achat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdrstdocument',
            name='demandeur',
            field=models.ForeignKey(db_column='demandeur_id', on_delete=django.db.models.deletion.PROTECT, related_name='tdr_st_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
