# Generated by Django 5.2.10 on 2026-03-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0003_workflowhistory_alter_demandeachat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bc', models.CharField(max_length=100)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('receptionnaire', models.CharField(max_length=255)),
                ('statut_reception', models.CharField(default='En attente', max_length=50)),
                ('bon_livraison_file', models.FileField(blank=True, null=True, upload_to='receptions/bl/')),
                ('pv_reception_file', models.FileField(blank=True, null=True, upload_to='receptions/pv/')),
                ('observations_generales', models.TextField(blank=True, null=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='achats.demandeachat')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite_commandee', models.IntegerField()),
                ('quantite_reçue', models.IntegerField()),
                ('etat_qualite', models.CharField(max_length=50)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reception.reception')),
            ],
        ),
        migrations.CreateModel(
            name='Ecart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(max_length=100)),
                ('description_probleme', models.TextField()),
                ('action_corrective', models.CharField(max_length=100)),
                ('resolu', models.BooleanField(default=False)),
                ('reception_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.receptionitem')),
            ],
        ),
    ]
