# Generated by Django 5.2.10 on 2026-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=50, unique=True)),
                ('date_demande', models.DateField()),
                ('service', models.CharField(max_length=200)),
                ('demandeur', models.CharField(max_length=200)),
                ('fonction_demandeur', models.CharField(max_length=200)),
                ('statut', models.CharField(default='brouillon', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
