# Generated by Django 5.2.10 on 2026-03-29 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(blank=True, max_length=30, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('unite_technique', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('A_COMPLETER', 'A completer'), ('VALIDEE', 'Validee'), ('REJETEE', 'Rejetee')], default='BROUILLON', max_length=20)),
                ('categorie_besoin', models.CharField(choices=[('NOUVEAU_BESOIN', 'Nouveau besoin'), ('REAPPROVISIONNEMENT', 'Reapprovisionnement stock'), ('REMPLACEMENT', 'Remplacement equipement defectueux'), ('URGENCE', 'Urgence operationnelle')], max_length=30)),
                ('type_demande', models.CharField(choices=[('MATERIELS', 'Materiels'), ('PETITS_SERVICES', 'Petits services'), ('SERVICES_RECURRENTS', 'Services recurrents')], max_length=30)),
                ('priorite', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10)),
                ('objet', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('lien_ptba', models.CharField(max_length=255)),
                ('service_beneficiaire', models.CharField(max_length=255)),
                ('ligne_budgetaire', models.CharField(max_length=100)),
                ('source_financement', models.CharField(choices=[('FONDS_MONDIAL', 'Fonds mondial'), ('BANQUE_MONDIALE', 'Banque mondiale'), ('GAVI', 'Alliance Gavi')], max_length=30)),
                ('cout_total_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('SPECIFICATIONS_TECHNIQUES', 'Specifications techniques detaillees'), ('TDR_SIMPLIFIE', 'Termes de Reference simplifies'), ('DEVIS_ESTIMATIF', 'Devis estimatif'), ('BON_SORTIE_STOCK', 'Bon de sortie stock')], max_length=40)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='demandes/documents/')),
                ('commentaire', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='achats.demandeachat')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LigneBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('marque_modele', models.CharField(blank=True, max_length=255)),
                ('caracteristiques_techniques', models.TextField(blank=True)),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('prix_unitaire_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cout_total_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lieu_livraison', models.CharField(blank=True, max_length=255)),
                ('destinataire_final', models.CharField(blank=True, max_length=255)),
                ('type_service', models.CharField(blank=True, choices=[('FORMATION', 'Formation'), ('MAINTENANCE', 'Maintenance'), ('REPARATION', 'Reparation'), ('NETTOYAGE', 'Nettoyage'), ('PRESTATION_PONCTUELLE', 'Prestation ponctuelle')], max_length=30)),
                ('description_service', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_estimee', models.CharField(blank=True, max_length=100)),
                ('lieu_execution', models.CharField(blank=True, max_length=255)),
                ('livrables_attendus', models.TextField(blank=True)),
                ('nombre_beneficiaires', models.PositiveIntegerField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_besoin', to='achats.demandeachat')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
