# Generated by Django 5.2.10 on 2026-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(blank=True, max_length=30, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('unite_technique', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('A_COMPLETER', 'A completer'), ('VALIDEE', 'Validee'), ('VALIDEE_BUDGETAIRE', 'Validee budgetairement'), ('EN_COMMANDE', 'En commande'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livree'), ('CLOTUREE', 'Cloturee'), ('REJETEE', 'Rejetee')], default='BROUILLON', max_length=20)),
                ('etape_validation_actuelle', models.CharField(choices=[('HIERARCHIQUE', 'Validation hierarchique'), ('TECHNIQUE', 'Validation technique'), ('BUDGETAIRE', 'Validation budgetaire'), ('PROGRAMMATIQUE', 'Validation programmatique'), ('APPROBATION_FINALE', 'Approbation finale'), ('TERMINEE', 'Terminee')], default='HIERARCHIQUE', max_length=30)),
                ('categorie_besoin', models.CharField(choices=[('NOUVEAU_BESOIN', 'Nouveau besoin'), ('REAPPROVISIONNEMENT', 'Reapprovisionnement stock'), ('REMPLACEMENT', 'Remplacement equipement defectueux'), ('URGENCE', 'Urgence operationnelle')], max_length=30)),
                ('type_demande', models.CharField(choices=[('MATERIELS', 'Materiels'), ('PETITS_SERVICES', 'Petits services'), ('SERVICES_RECURRENTS', 'Services recurrents')], max_length=30)),
                ('priorite', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10)),
                ('objet', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('lien_ptba', models.CharField(max_length=255)),
                ('service_beneficiaire', models.CharField(max_length=255)),
                ('requires_tdr', models.BooleanField(default=False)),
                ('ligne_budgetaire', models.CharField(blank=True, max_length=100)),
                ('source_financement', models.CharField(blank=True, choices=[('SRPS_CS7_FM', 'SRPS / CS7 / Fonds Mondial'), ('RSS3_GAVI', 'RSS3 / Alliance GAVI'), ('FAE_GAVI', 'FAE / Alliance GAVI'), ('CDS_GAVI', 'CDS / Alliance GAVI'), ('VAR_GAVI', 'VAR / Alliance GAVI'), ('PARN2_BM', 'PARN2 / Banque Mondiale'), ('PPSB_BM', 'PPSB / Banque Mondiale')], max_length=30)),
                ('numero_subvention', models.CharField(blank=True, max_length=100)),
                ('solde_disponible_ligne_budgetaire', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('numero_engagement_budgetaire', models.CharField(blank=True, max_length=100)),
                ('solde_apres_engagement', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cout_total_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('type_procedure', models.CharField(blank=True, choices=[('DEMANDE_COTATION', 'Demande de cotation'), ('BON_COMMANDE_DIRECT', 'Bon de commande direct'), ('SELECTION_APRES_COTATION', 'Selection apres cotation')], max_length=30)),
                ('fournisseur_retenu', models.CharField(blank=True, max_length=255)),
                ('email_fournisseur', models.EmailField(blank=True, max_length=254)),
                ('numero_bon_commande', models.CharField(blank=True, max_length=30)),
                ('date_bon_commande', models.DateField(blank=True, null=True)),
                ('montant_commande', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('delai_livraison_contractuel', models.PositiveIntegerField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('conditions_livraison', models.CharField(blank=True, max_length=255)),
                ('garantie', models.CharField(blank=True, max_length=255)),
                ('date_arrivee_prevue', models.DateField(blank=True, null=True)),
                ('date_arrivee_effective', models.DateField(blank=True, null=True)),
                ('etat_expedition', models.CharField(blank=True, choices=[('EN_TRANSIT', 'En transit'), ('ARRIVE', 'Arrive'), ('PARTIEL', 'Partiel'), ('RETARD', 'Retard')], max_length=20)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('receptionnaire', models.CharField(blank=True, max_length=255)),
                ('conformite_quantite', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('PARTIELLE', 'Partielle')], max_length=20)),
                ('conformite_qualite', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('DEFECTUEUX', 'Defectueux')], max_length=20)),
                ('observations_reception', models.TextField(blank=True)),
                ('statut_reception', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RECEPTION_PARTIELLE', 'Reception partielle'), ('RECEPTION_COMPLETE', 'Reception complete'), ('ECART_DETECTE', 'Ecart detecte'), ('ECART_RESOLU', 'Ecart resolu')], default='EN_ATTENTE', max_length=30)),
                ('type_ecart', models.CharField(blank=True, choices=[('MANQUANT', 'Manquant'), ('DEFECTUEUX', 'Defectueux'), ('NON_CONFORME', 'Non conforme'), ('HORS_SPECIFICATIONS', 'Hors specifications')], max_length=30)),
                ('description_ecart', models.TextField(blank=True)),
                ('action_corrective', models.CharField(blank=True, choices=[('REMPLACEMENT', 'Remplacement'), ('REPARATION', 'Reparation'), ('AVOIR', 'Avoir'), ('REJET', 'Rejet')], max_length=30)),
                ('date_resolution', models.DateField(blank=True, null=True)),
                ('suivi_resolution', models.TextField(blank=True)),
                ('statut_final', models.CharField(blank=True, choices=[('CLOTURE', 'Cloture'), ('PARTIELLEMENT_EXECUTE', 'Partiellement execute'), ('ANNULE', 'Annule')], max_length=30)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('niveau_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentaires_finaux', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('SPECIFICATIONS_TECHNIQUES', 'Specifications techniques detaillees'), ('TDR_SIMPLIFIE', 'Termes de Reference simplifies'), ('DEVIS_ESTIMATIF', 'Devis estimatif'), ('BON_SORTIE_STOCK', 'Bon de sortie stock'), ('BON_LIVRAISON', 'Bon de livraison'), ('PV_RECEPTION', 'Proces-verbal de reception')], max_length=40)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='demandes/documents/')),
                ('commentaire', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEMANDE_CREEE', 'Demande créée'), ('DEMANDE_SOUMISE', 'Demande soumise'), ('VALIDATION', 'Validation enregistrée'), ('BUDGET_VALIDE', 'Budget validé'), ('COMMANDE_EMISE', 'Commande émise'), ('LIVRAISON_MISE_A_JOUR', 'Livraison mise à jour'), ('RECEPTION_ENREGISTREE', 'Réception enregistrée'), ('ECART_RESOLU', 'Écart résolu'), ('DEMANDE_CLOTUREE', 'Demande clôturée'), ('RAPPEL_VALIDATION_24H', 'Rappel validation 24h')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('marque_modele', models.CharField(blank=True, max_length=255)),
                ('caracteristiques_techniques', models.TextField(blank=True)),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('prix_unitaire_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cout_total_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lieu_livraison', models.CharField(blank=True, max_length=255)),
                ('destinataire_final', models.CharField(blank=True, max_length=255)),
                ('type_service', models.CharField(blank=True, choices=[('FORMATION', 'Formation'), ('MAINTENANCE', 'Maintenance'), ('REPARATION', 'Reparation'), ('NETTOYAGE', 'Nettoyage'), ('PRESTATION_PONCTUELLE', 'Prestation ponctuelle')], max_length=30)),
                ('description_service', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_estimee', models.CharField(blank=True, max_length=100)),
                ('lieu_execution', models.CharField(blank=True, max_length=255)),
                ('livrables_attendus', models.TextField(blank=True)),
                ('nombre_beneficiaires', models.PositiveIntegerField(blank=True, null=True)),
                ('quantite_recue', models.PositiveIntegerField(blank=True, null=True)),
                ('observation_reception', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('HIERARCHIQUE', 'Validation hierarchique'), ('TECHNIQUE', 'Validation technique'), ('BUDGETAIRE', 'Validation budgetaire'), ('PROGRAMMATIQUE', 'Validation programmatique'), ('APPROBATION_FINALE', 'Approbation finale'), ('TERMINEE', 'Terminee')], max_length=30)),
                ('decision', models.CharField(choices=[('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Defavorable'), ('A_COMPLETER', 'A completer'), ('APPROUVEE', 'Approuvee'), ('REJETEE', 'Rejetee'), ('A_REVOIR', 'A revoir')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('donnees_etape', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
