# Generated by Django 5.2.10 on 2026-03-18 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=50, unique=True)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('service_demandeur', models.CharField(max_length=200)),
                ('fonction_demandeur', models.CharField(max_length=200)),
                ('activite_ptba', models.CharField(max_length=255)),
                ('indicateur_performance', models.CharField(blank=True, max_length=255, null=True)),
                ('source_financement', models.CharField(choices=[('FONDS_MONDIAL', 'Fonds Mondial'), ('GAVI', 'Gavi'), ('BANQUE_MONDIALE', 'Banque mondiale'), ('BUDGET_ETAT', 'Budget Etat'), ('AUTRE', 'Autre')], max_length=50)),
                ('ligne_budgetaire', models.CharField(max_length=100)),
                ('budget_estime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(max_length=10)),
                ('type_marche', models.CharField(choices=[('BIENS', 'Biens'), ('SERVICES', 'Services'), ('TRAVAUX', 'Travaux')], max_length=20)),
                ('nature_activite', models.CharField(choices=[('FORMATION', 'Formation'), ('REUNION', 'Réunion'), ('SUPERVISION', 'Supervision'), ('REVUE', 'Revue'), ('CONSTRUCTION', 'Construction'), ('AUTRE', 'Autre')], max_length=50)),
                ('objet_demande', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='demandes/')),
                ('region', models.CharField(max_length=200)),
                ('adresse_livraison', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('urgent', models.BooleanField(default=False)),
                ('justification_urgence', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='BROUILLON', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='achats.demandeachat')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
