# Generated by Django 5.2.10 on 2026-03-19 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeachat',
            old_name='piece_jointe',
            new_name='pieces_jointes',
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='validationdemande',
            name='role',
            field=models.CharField(blank=True, choices=[('SERVICE', 'Responsable service'), ('BUDGET', 'Contrôleur budget'), ('DIRECTION', 'Directeur')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='adresse_livraison',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='devise',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='nature_activite',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='source_financement',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDE_SERVICE', 'Validée service'), ('VALIDE_BUDGET', 'Validée budget'), ('VALIDE_DIRECTION', 'Validée direction'), ('REJETEE', 'Rejetée'), ('TRANSMISE_MARCHES', 'Transmise aux marchés')], default='BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='validationdemande',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
