# Generated by Django 5.2.10 on 2026-07-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='achats.demandeachat'),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to='achats.fournisseur'),
        ),
        migrations.AddField(
            model_name='historiquedemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='achats.demandeachat'),
        ),
        migrations.AddField(
            model_name='historiquedemande',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_achats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignebesoin',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_besoin', to='achats.demandeachat'),
        ),
        migrations.AddField(
            model_name='validationdemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='achats.demandeachat'),
        ),
        migrations.AddField(
            model_name='validationdemande',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_achat', to=settings.AUTH_USER_MODEL),
        ),
    ]
