# Generated by Django 5.2.10 on 2026-08-25 11:23

import apps.achats.models.demande_achat
import apps.achats.models.document_demande
import apps.achats.models.historique_demande
import apps.achats.models.ligne_besoin
import apps.achats.models.validation_demande
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='action_corrective',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._action_corrective_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='categorie_besoin',
            field=models.CharField(choices=apps.achats.models.demande_achat._categorie_besoin_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='conformite_qualite',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._conformite_qualite_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='conformite_quantite',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._conformite_quantite_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='etape_validation_actuelle',
            field=models.CharField(choices=apps.achats.models.demande_achat._etape_validation_achat_choices, default='HIERARCHIQUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='etat_expedition',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._etat_expedition_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='priorite',
            field=models.CharField(choices=apps.achats.models.demande_achat._priorite_choices, default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='source_financement',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._source_financement_detail_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=apps.achats.models.demande_achat._statut_demande_achat_choices, default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut_final',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._statut_final_achat_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut_reception',
            field=models.CharField(choices=apps.achats.models.demande_achat._statut_reception_choices, default='EN_ATTENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='type_demande',
            field=models.CharField(choices=apps.achats.models.demande_achat._type_demande_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='type_ecart',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._type_ecart_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='type_procedure',
            field=models.CharField(blank=True, choices=apps.achats.models.demande_achat._type_procedure_achat_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='documentdemande',
            name='type_document',
            field=models.CharField(choices=apps.achats.models.document_demande._type_document_achat_choices, max_length=40),
        ),
        migrations.AlterField(
            model_name='historiquedemande',
            name='action',
            field=models.CharField(choices=apps.achats.models.historique_demande._action_historique_achat_choices, max_length=40),
        ),
        migrations.AlterField(
            model_name='lignebesoin',
            name='type_service',
            field=models.CharField(blank=True, choices=apps.achats.models.ligne_besoin._type_service_achat_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='validationdemande',
            name='decision',
            field=models.CharField(choices=apps.achats.models.validation_demande._decision_validation_choices, max_length=20),
        ),
    ]
