# Generated by Django 5.2.10 on 2026-03-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_rename_piece_jointe_demandeachat_pieces_jointes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('SUBMIT', 'Soumission'), ('APPROVE', 'Validation'), ('REJECT', 'Rejet'), ('TRANSMIT', 'Transmission marchés')], max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='demandeachat',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='validationdemande',
            options={'ordering': ('date_validation',)},
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_transmission_marches',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationdemande',
            name='fonds_statut',
            field=models.CharField(blank=True, choices=[('DISPONIBLES', 'Fonds disponibles'), ('INSUFFISANTS', 'Fonds insuffisants')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='validationdemande',
            name='visa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDE_SERVICE', 'Validée service'), ('VALIDE_BUDGET', 'Validée budget'), ('VALIDE_DIRECTION', 'Validée direction'), ('REJETEE', 'Rejetée'), ('TRANSMISE_MARCHES', 'Transmise aux marchés')], db_index=True, default='BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='validationdemande',
            name='role',
            field=models.CharField(choices=[('SERVICE', 'Responsable service'), ('BUDGET', 'Contrôleur budget'), ('DIRECTION', 'Directeur')], default='SERVICE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationdemande',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_achat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='validationdemande',
            constraint=models.UniqueConstraint(fields=('demande', 'role'), name='unique_validation_role_per_demande'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='achats.demandeachat'),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
