# Generated by Django 5.2.10 on 2026-03-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_validationdemande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='etape_validation_actuelle',
            field=models.CharField(choices=[('HIERARCHIQUE', 'Validation hierarchique'), ('TECHNIQUE', 'Validation technique'), ('BUDGETAIRE', 'Validation budgetaire'), ('PROGRAMMATIQUE', 'Validation programmatique'), ('APPROBATION_FINALE', 'Approbation finale'), ('TERMINEE', 'Terminee')], default='HIERARCHIQUE', max_length=30),
        ),
    ]
