# Generated by Django 5.2.10 on 2026-03-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_demandeachat_etape_validation_actuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationdemande',
            name='donnees_etape',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='validationdemande',
            name='etape',
            field=models.CharField(choices=[('HIERARCHIQUE', 'Validation hierarchique'), ('TECHNIQUE', 'Validation technique'), ('BUDGETAIRE', 'Validation budgetaire'), ('PROGRAMMATIQUE', 'Validation programmatique'), ('APPROBATION_FINALE', 'Approbation finale'), ('TERMINEE', 'Terminee')], default='HIERARCHIQUE', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationdemande',
            name='decision',
            field=models.CharField(choices=[('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Defavorable'), ('A_COMPLETER', 'A completer'), ('APPROUVEE', 'Approuvee'), ('REJETEE', 'Rejetee'), ('A_REVOIR', 'A revoir')], max_length=20),
        ),
    ]
