# Generated by Django 5.2.10 on 2026-08-25 11:42

import apps.achats.models.demande_achat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_alter_demandeachat_action_corrective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationdemande',
            name='etape',
            field=models.CharField(choices=apps.achats.models.demande_achat._etape_validation_achat_choices, max_length=30),
        ),
    ]
