# Generated by Django 5.2.10 on 2026-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_validationdemande_donnees_etape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='action_corrective',
            field=models.CharField(blank=True, choices=[('REMPLACEMENT', 'Remplacement'), ('REPARATION', 'Reparation'), ('AVOIR', 'Avoir'), ('REJET', 'Rejet')], max_length=30),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='commentaires_finaux',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='conditions_livraison',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='conformite_qualite',
            field=models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('DEFECTUEUX', 'Defectueux')], max_length=20),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='conformite_quantite',
            field=models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('PARTIELLE', 'Partielle')], max_length=20),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_arrivee_effective',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_arrivee_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_bon_commande',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='date_resolution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='delai_livraison_contractuel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='description_ecart',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='etat_expedition',
            field=models.CharField(blank=True, choices=[('EN_TRANSIT', 'En transit'), ('ARRIVE', 'Arrive'), ('PARTIEL', 'Partiel'), ('RETARD', 'Retard')], max_length=20),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='fournisseur_retenu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='garantie',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='montant_commande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='niveau_satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='numero_bon_commande',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='numero_engagement_budgetaire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='numero_subvention',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='observations_reception',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='receptionnaire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='solde_apres_engagement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='solde_disponible_ligne_budgetaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='statut_final',
            field=models.CharField(blank=True, choices=[('CLOTURE', 'Cloture'), ('PARTIELLEMENT_EXECUTE', 'Partiellement execute'), ('ANNULE', 'Annule')], max_length=30),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='statut_reception',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RECEPTION_PARTIELLE', 'Reception partielle'), ('RECEPTION_COMPLETE', 'Reception complete')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='suivi_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='type_ecart',
            field=models.CharField(blank=True, choices=[('MANQUANT', 'Manquant'), ('DEFECTUEUX', 'Defectueux'), ('NON_CONFORME', 'Non conforme'), ('HORS_SPECIFICATIONS', 'Hors specifications')], max_length=30),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='type_procedure',
            field=models.CharField(blank=True, choices=[('DEMANDE_COTATION', 'Demande de cotation'), ('BON_COMMANDE_DIRECT', 'Bon de commande direct')], max_length=30),
        ),
        migrations.AddField(
            model_name='lignebesoin',
            name='observation_reception',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lignebesoin',
            name='quantite_recue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('A_COMPLETER', 'A completer'), ('VALIDEE', 'Validee'), ('EN_COMMANDE', 'En commande'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livree'), ('CLOTUREE', 'Cloturee'), ('REJETEE', 'Rejetee')], default='BROUILLON', max_length=20),
        ),
    ]
