# Generated by Django 5.2.10 on 2026-03-31 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_demandeachat_action_corrective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEMANDE_CREEE', 'Demande créée'), ('DEMANDE_SOUMISE', 'Demande soumise'), ('VALIDATION', 'Validation enregistrée'), ('COMMANDE_EMISE', 'Commande émise'), ('LIVRAISON_MISE_A_JOUR', 'Livraison mise à jour'), ('RECEPTION_ENREGISTREE', 'Réception enregistrée'), ('DEMANDE_CLOTUREE', 'Demande clôturée')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='achats.demandeachat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_achats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
