# Generated by Django 5.2.10 on 2026-04-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_historiquedemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='type_procedure',
            field=models.CharField(blank=True, choices=[('DEMANDE_COTATION', 'Demande de cotation'), ('BON_COMMANDE_DIRECT', 'Bon de commande direct'), ('SELECTION_APRES_COTATION', 'Selection apres cotation')], max_length=30),
        ),
    ]
