# Generated by Django 5.2.10 on 2026-04-16 03:06

from django.db import migrations, models


def migrate_old_budget_validation_step(apps, schema_editor):
    DemandeAchat = apps.get_model("achats", "DemandeAchat")
    DemandeAchat.objects.filter(
        statut="SOUMISE",
        etape_validation_actuelle="BUDGETAIRE",
    ).update(etape_validation_actuelle="PROGRAMMATIQUE")


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0007_alter_demandeachat_type_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='ligne_budgetaire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='source_financement',
            field=models.CharField(blank=True, choices=[('FONDS_MONDIAL', 'Fonds mondial'), ('BANQUE_MONDIALE', 'Banque mondiale'), ('GAVI', 'Alliance Gavi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('A_COMPLETER', 'A completer'), ('VALIDEE', 'Validee'), ('VALIDEE_BUDGETAIRE', 'Validee budgetairement'), ('EN_COMMANDE', 'En commande'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livree'), ('CLOTUREE', 'Cloturee'), ('REJETEE', 'Rejetee')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut_reception',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RECEPTION_PARTIELLE', 'Reception partielle'), ('RECEPTION_COMPLETE', 'Reception complete'), ('ECART_DETECTE', 'Ecart detecte'), ('ECART_RESOLU', 'Ecart resolu')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentdemande',
            name='type_document',
            field=models.CharField(choices=[('SPECIFICATIONS_TECHNIQUES', 'Specifications techniques detaillees'), ('TDR_SIMPLIFIE', 'Termes de Reference simplifies'), ('DEVIS_ESTIMATIF', 'Devis estimatif'), ('BON_SORTIE_STOCK', 'Bon de sortie stock'), ('BON_LIVRAISON', 'Bon de livraison'), ('PV_RECEPTION', 'Proces-verbal de reception')], max_length=40),
        ),
        migrations.AlterField(
            model_name='historiquedemande',
            name='action',
            field=models.CharField(choices=[('DEMANDE_CREEE', 'Demande créée'), ('DEMANDE_SOUMISE', 'Demande soumise'), ('VALIDATION', 'Validation enregistrée'), ('BUDGET_VALIDE', 'Budget validé'), ('COMMANDE_EMISE', 'Commande émise'), ('LIVRAISON_MISE_A_JOUR', 'Livraison mise à jour'), ('RECEPTION_ENREGISTREE', 'Réception enregistrée'), ('ECART_RESOLU', 'Écart résolu'), ('DEMANDE_CLOTUREE', 'Demande clôturée')], max_length=40),
        ),
        migrations.RunPython(
            migrate_old_budget_validation_step,
            migrations.RunPython.noop,
        ),
    ]
