# Generated by Codex on 2026-04-16

from django.db import migrations


def create_finance_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="FINANCE")


def delete_finance_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="FINANCE").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("achats", "0008_alter_demandeachat_ligne_budgetaire_and_more"),
    ]

    operations = [
        migrations.RunPython(create_finance_group, delete_finance_group),
    ]
