# Generated by Django 5.2.10 on 2026-04-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0009_create_finance_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeachat',
            name='source_financement',
            field=models.CharField(blank=True, choices=[('SRPS_CS7_FM', 'SRPS / CS7 / Fonds Mondial'), ('RSS3_GAVI', 'RSS3 / Alliance GAVI'), ('FAE_GAVI', 'FAE / Alliance GAVI'), ('CDS_GAVI', 'CDS / Alliance GAVI'), ('VAR_GAVI', 'VAR / Alliance GAVI'), ('PARN2_BM', 'PARN2 / Banque Mondiale'), ('PPSB_BM', 'PPSB / Banque Mondiale')], max_length=30),
        ),
    ]
