# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0012_fournisseur_demandeachat_fournisseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeachat",
            name="requires_tdr",
            field=models.BooleanField(default=False),
        ),
    ]
