# Generated by Django 5.2.10 on 2026-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0013_demandeachat_requires_tdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquedemande',
            name='action',
            field=models.CharField(choices=[('DEMANDE_CREEE', 'Demande créée'), ('DEMANDE_SOUMISE', 'Demande soumise'), ('VALIDATION', 'Validation enregistrée'), ('BUDGET_VALIDE', 'Budget validé'), ('COMMANDE_EMISE', 'Commande émise'), ('LIVRAISON_MISE_A_JOUR', 'Livraison mise à jour'), ('RECEPTION_ENREGISTREE', 'Réception enregistrée'), ('ECART_RESOLU', 'Écart résolu'), ('DEMANDE_CLOTUREE', 'Demande clôturée'), ('RAPPEL_VALIDATION_24H', 'Rappel validation 24h')], max_length=40),
        ),
    ]
