# Generated by Django 6.0.1 on 2026-01-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travaux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=255)),
                ('montant_estimatif', models.DecimalField(decimal_places=2, max_digits=15)),
                ('agmo', models.CharField(max_length=255)),
                ('methode_pm', models.CharField(max_length=255)),
                ('approches', models.CharField(max_length=255)),
                ('revue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'travaux',
            },
        ),
        migrations.CreateModel(
            name='TravauxDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prevuxreel', models.CharField(max_length=255)),
                ('listesetspecifications', models.DateField(blank=True, null=True)),
                ('dossiers_appel', models.DateField(blank=True, null=True)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('rapport_evaluation', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField()),
                ('travaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marches.travaux')),
            ],
            options={
                'db_table': 'travaux_details',
            },
        ),
    ]
