# Generated by Django 6.0.1 on 2026-01-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0003_travauxdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravauxDetail',
        ),
    ]
