# Generated by Django 6.0.1 on 2026-01-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0005_travauxdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travauxdetail',
            name='travaux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marches.travaux'),
        ),
    ]
