# Generated by Django 6.0.1 on 2026-01-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0006_alter_travauxdetail_travaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=255)),
                ('montant_estimatif', models.DecimalField(decimal_places=2, max_digits=15)),
                ('agmo', models.CharField(max_length=255)),
                ('methode_epm', models.CharField(max_length=255)),
                ('approches', models.CharField(max_length=255)),
                ('revue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'biens',
            },
        ),
        migrations.CreateModel(
            name='BiensDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prevuxreel', models.CharField(max_length=255)),
                ('listesetspecifications', models.DateField(blank=True, null=True)),
                ('dossiers_appel', models.DateField(blank=True, null=True)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('rapport_evaluation', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('biens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marches.biens')),
            ],
            options={
                'db_table': 'biens_details',
            },
        ),
    ]
