# Generated by Django 6.0.1 on 2026-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0007_biens_biensdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='biens',
            name='code_suivi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='code_suivi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
