# Generated by Django 6.0.1 on 2026-01-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0008_biens_code_suivi_travaux_code_suivi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_code_suivi', models.CharField(blank=True, max_length=100, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('agmoxdirection', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_estimatif', models.DecimalField(decimal_places=2, max_digits=15)),
                ('methode', models.CharField(max_length=255)),
                ('approche', models.CharField(max_length=255)),
                ('revue', models.CharField(max_length=255)),
                ('forfaitxtemps', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'consultance',
            },
        ),
        migrations.CreateModel(
            name='ConsultanceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TdR', models.DateField(blank=True, null=True)),
                ('ami', models.DateField(blank=True, null=True)),
                ('liste_restreinte', models.DateField(blank=True, null=True)),
                ('demande_proposition', models.DateField(blank=True, null=True)),
                ('date_invitation', models.DateField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('rapport_evaluation', models.DateField(blank=True, null=True)),
                ('ouverture_plis', models.DateField(blank=True, null=True)),
                ('projet_contrat', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('consultance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marches.consultance')),
            ],
            options={
                'db_table': 'consultance_details',
            },
        ),
    ]
