# Generated by Django 6.0.1 on 2026-01-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0009_consultance_consultancedetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiensDetail',
            new_name='BiensDetails',
        ),
        migrations.RenameModel(
            old_name='ConsultanceDetail',
            new_name='ConsultanceDetails',
        ),
        migrations.RenameModel(
            old_name='TravauxDetail',
            new_name='TravauxDetails',
        ),
    ]
