# Generated by Django 6.0.1 on 2026-02-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0010_rename_biensdetail_biensdetails_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravauxDetails',
            new_name='TravauxDetailsPrevu',
        ),
        migrations.RenameField(
            model_name='travauxdetailsprevu',
            old_name='prevuxreel',
            new_name='prevu',
        ),
        migrations.AlterModelTable(
            name='travauxdetailsprevu',
            table='travaux_details_prevu',
        ),
        migrations.CreateModel(
            name='TravauxDetailsReel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reel', models.CharField(max_length=255)),
                ('listesetspecifications', models.DateField(blank=True, null=True)),
                ('dossiers_appel', models.DateField(blank=True, null=True)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('rapport_evaluation', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('travaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marches.travaux')),
            ],
            options={
                'db_table': 'travaux_details_reel',
            },
        ),
    ]
