# Generated by Django 6.0.1 on 2026-02-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0011_rename_travauxdetails_travauxdetailsprevu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultanceDetails',
            new_name='ConsultanceDetailsPrevu',
        ),
        migrations.AlterModelTable(
            name='consultancedetailsprevu',
            table='consultance_details_prevu',
        ),
        migrations.CreateModel(
            name='ConsultanceDetailsReel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TdR', models.DateField(blank=True, null=True)),
                ('ami', models.DateField(blank=True, null=True)),
                ('liste_restreinte', models.DateField(blank=True, null=True)),
                ('demande_proposition', models.DateField(blank=True, null=True)),
                ('date_invitation', models.DateField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('rapport_evaluation', models.DateField(blank=True, null=True)),
                ('ouverture_plis', models.DateField(blank=True, null=True)),
                ('projet_contrat', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('consultance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marches.consultance')),
            ],
            options={
                'db_table': 'consultance_details_reel',
            },
        ),
    ]
