# Generated by Django 6.0.1 on 2026-02-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0012_rename_consultancedetails_consultancedetailsprevu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiensDetails',
            new_name='BiensDetailsPrevu',
        ),
        migrations.RenameField(
            model_name='biensdetailsprevu',
            old_name='prevuxreel',
            new_name='prevu',
        ),
        migrations.AlterModelTable(
            name='biensdetailsprevu',
            table='biens_details_prevu',
        ),
        migrations.CreateModel(
            name='BiensDetailsReel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reel', models.CharField(max_length=255)),
                ('listesetspecifications', models.DateField(blank=True, null=True)),
                ('dossiers_appel', models.DateField(blank=True, null=True)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('rapport_evaluation', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('biens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marches.biens')),
            ],
            options={
                'db_table': 'biens_details_reel',
            },
        ),
    ]
