# Generated by Django 5.2.10 on 2026-02-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0013_rename_biensdetails_biensdetailsprevu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travauxdetailsreel',
            name='travaux',
        ),
        migrations.AddField(
            model_name='biensdetailsprevu',
            name='duree',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='consultancedetailsprevu',
            name='duree',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='travaux',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_lancement_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_lancement_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_livraison_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_livraison_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_ouverture_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_ouverture_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_signature_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='date_signature_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='dossiers_appel_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='dossiers_appel_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='duree',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='travaux',
            name='listesetspecifications',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='prevu',
            field=models.CharField(default='Prévu', max_length=255),
        ),
        migrations.AddField(
            model_name='travaux',
            name='rapport_evaluation_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='rapport_evaluation_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TravauxDetailsPrevu',
        ),
        migrations.DeleteModel(
            name='TravauxDetailsReel',
        ),
    ]
