# Generated by Django 5.2.10 on 2026-02-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0014_remove_travauxdetailsreel_travaux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biensdetailsreel',
            name='biens',
        ),
        migrations.RemoveField(
            model_name='consultancedetailsprevu',
            name='consultance',
        ),
        migrations.RemoveField(
            model_name='consultancedetailsreel',
            name='consultance',
        ),
        migrations.AddField(
            model_name='biens',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_lancement_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_lancement_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_livraison_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_livraison_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_ouverture_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_ouverture_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_signature_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='date_signature_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='dossiers_appel_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='dossiers_appel_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='duree',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='biens',
            name='listesetspecifications',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='prevu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='rapport_evaluation_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='rapport_evaluation_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='reel',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='statut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='TdR_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='TdR_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='ami_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='ami_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_fin_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_fin_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_invitation_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_invitation_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_ouverture_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_ouverture_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_signature_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='date_signature_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='demande_proposition_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='demande_proposition_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='duree',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='consultance',
            name='liste_restreinte_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='liste_restreinte_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='ouverture_plis_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='ouverture_plis_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='projet_contrat_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='projet_contrat_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='rapport_evaluation_prevu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='rapport_evaluation_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='statut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='reel',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='statut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='prevu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BiensDetailsPrevu',
        ),
        migrations.DeleteModel(
            name='BiensDetailsReel',
        ),
        migrations.DeleteModel(
            name='ConsultanceDetailsPrevu',
        ),
        migrations.DeleteModel(
            name='ConsultanceDetailsReel',
        ),
    ]
