# Generated by Django 5.2.10 on 2026-03-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_code_suivi', models.CharField(blank=True, max_length=100, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('agmoxdirection', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_estimatif', models.DecimalField(decimal_places=2, max_digits=15)),
                ('methode', models.CharField(max_length=255)),
                ('approche', models.CharField(max_length=255)),
                ('revue', models.CharField(max_length=255)),
                ('forfaitxtemps', models.CharField(blank=True, max_length=255, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('TdR_prevu', models.DateField(blank=True, null=True)),
                ('ami_prevu', models.DateField(blank=True, null=True)),
                ('liste_restreinte_prevu', models.DateField(blank=True, null=True)),
                ('demande_proposition_prevu', models.DateField(blank=True, null=True)),
                ('date_invitation_prevu', models.DateField(blank=True, null=True)),
                ('date_ouverture_prevu', models.DateField(blank=True, null=True)),
                ('rapport_evaluation_prevu', models.DateField(blank=True, null=True)),
                ('ouverture_plis_prevu', models.DateField(blank=True, null=True)),
                ('projet_contrat_prevu', models.DateField(blank=True, null=True)),
                ('date_signature_prevu', models.DateField(blank=True, null=True)),
                ('date_fin_prevu', models.DateField(blank=True, null=True)),
                ('duree', models.IntegerField(default=60)),
                ('TdR_reel', models.DateField(blank=True, null=True)),
                ('ami_reel', models.DateField(blank=True, null=True)),
                ('liste_restreinte_reel', models.DateField(blank=True, null=True)),
                ('demande_proposition_reel', models.DateField(blank=True, null=True)),
                ('date_invitation_reel', models.DateField(blank=True, null=True)),
                ('date_ouverture_reel', models.DateField(blank=True, null=True)),
                ('rapport_evaluation_reel', models.DateField(blank=True, null=True)),
                ('ouverture_plis_reel', models.DateField(blank=True, null=True)),
                ('projet_contrat_reel', models.DateField(blank=True, null=True)),
                ('date_signature_reel', models.DateField(blank=True, null=True)),
                ('date_fin_reel', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultance',
            },
        ),
        migrations.DeleteModel(
            name='Consultances',
        ),
    ]
