# Generated by Django 5.2.10 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biens',
            old_name='listesetspecifications',
            new_name='listesetspecifications_prevu',
        ),
        migrations.RenameField(
            model_name='travaux',
            old_name='listesetspecifications',
            new_name='listesetspecifications_prevu',
        ),
        migrations.AddField(
            model_name='biens',
            name='listesetspecifications_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='listesetspecifications_reel',
            field=models.DateField(blank=True, null=True),
        ),
    ]
