# Generated by Django 5.2.10 on 2026-08-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biens',
            options={'verbose_name': 'Bien', 'verbose_name_plural': 'Biens'},
        ),
        migrations.AlterModelOptions(
            name='consultance',
            options={'verbose_name': 'Consultance', 'verbose_name_plural': 'Consultances'},
        ),
        migrations.AlterModelOptions(
            name='travaux',
            options={'verbose_name': 'Travaux', 'verbose_name_plural': 'Travaux'},
        ),
    ]
