# Generated by Django 5.2.10 on 2026-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0002_alter_biens_options_alter_consultance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biens',
            name='financing_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='biens',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biens',
            name='reference_bailleur',
            field=models.CharField(blank=True, choices=[('FM', 'Fonds Mondial'), ('GAVI', 'Alliance Gavi'), ('BM', 'Banque Mondiale')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='financing_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultance',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultance',
            name='reference_bailleur',
            field=models.CharField(blank=True, choices=[('FM', 'Fonds Mondial'), ('GAVI', 'Alliance Gavi'), ('BM', 'Banque Mondiale')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='financing_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='travaux',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travaux',
            name='reference_bailleur',
            field=models.CharField(blank=True, choices=[('FM', 'Fonds Mondial'), ('GAVI', 'Alliance Gavi'), ('BM', 'Banque Mondiale')], max_length=50, null=True),
        ),
    ]
