# Generated by Django 5.2.10 on 2026-05-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0002_rename_listesetspecifications_biens_listesetspecifications_prevu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biens',
            old_name='listesetspecifications_prevu',
            new_name='listesetspecifications',
        ),
        migrations.RenameField(
            model_name='travaux',
            old_name='listesetspecifications_prevu',
            new_name='listesetspecifications',
        ),
        migrations.RemoveField(
            model_name='biens',
            name='listesetspecifications_reel',
        ),
        migrations.RemoveField(
            model_name='travaux',
            name='listesetspecifications_reel',
        ),
    ]
