# Generated by Django 5.2.10 on 2026-05-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0008_alter_dateatelier_dates_atelier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_vues', to='procurement.procurementmarket')),
            ],
            options={
                'verbose_name': 'Log de Consultation',
            },
        ),
        migrations.CreateModel(
            name='LogDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('doc_type', models.CharField(choices=[('DAO', 'DAO Principal'), ('ANNEXE', 'Fichier Annexe')], max_length=10)),
                ('annexe_name', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_telechargements', to='procurement.procurementmarket')),
            ],
            options={
                'verbose_name': 'Log de Téléchargement',
            },
        ),
    ]
