# Generated by Django 5.2.10 on 2026-08-25 11:23

import apps.log.models.download
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdownload',
            name='doc_type',
            field=models.CharField(choices=apps.log.models.download._type_log_document_choices, max_length=10),
        ),
    ]
