# Generated by Django 5.2.10 on 2026-09-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_logdownload_doc_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logconsultation',
            options={'verbose_name': 'Log de Consultation', 'verbose_name_plural': 'Logs de Consultation'},
        ),
        migrations.AlterModelOptions(
            name='logdownload',
            options={'verbose_name': 'Log de Téléchargement', 'verbose_name_plural': 'Logs de Téléchargement'},
        ),
    ]
