# Generated by Django 5.2.10 on 2026-07-14 09:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrailContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('UPLOAD', 'Upload document'), ('SEND', 'Envoi au prestataire'), ('SIGN', 'Signature'), ('VALIDATE', 'Validation'), ('CANCEL', 'Annulation')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('champ_modifie', models.CharField(blank=True, max_length=100)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('navigateur', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_marche', models.CharField(help_text='Ex: UCP/DAO/2026/0001', max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ATTENTE_SIGNATURE', 'En attente de signature'), ('EXECUTION', 'En exécution'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('nom_prestataire', models.CharField(max_length=255)),
                ('email_prestataire', models.EmailField(max_length=254)),
                ('telephone_prestataire', models.CharField(blank=True, max_length=50)),
                ('nif_prestataire', models.CharField(blank=True, max_length=50)),
                ('stat_prestataire', models.CharField(blank=True, max_length=50)),
                ('representant_signataire', models.CharField(blank=True, max_length=255)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('duree_execution', models.CharField(blank=True, max_length=100)),
                ('clauses_particulieres', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CONTRAT_SIGNE', 'Contrat signé'), ('AVENANT', 'Avenant')], default='CONTRAT_SIGNE', max_length=20)),
                ('fichier', models.FileField(upload_to='contrats/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('hash_sha256', models.CharField(blank=True, help_text="Hash SHA256 du fichier pour vérifier l'intégrité", max_length=64)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='EcheancierPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pourcentage', models.IntegerField(help_text='Pourcentage du montant total (40, 30, 30)', validators=[django.core.validators.MinValueValidator(1)])),
                ('etape', models.CharField(help_text="Ex: 'Signature contrat', 'Livraison 50%', 'Livraison 100%'", max_length=200)),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('FACTURE_RECUE', 'Facture reçue'), ('PAYE', 'Payé')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_prevue'],
            },
        ),
    ]
