# Generated by Django 5.2.10 on 2026-07-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractualisation', '0001_initial'),
        ('ouverture_offre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrailcontrat',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='offre_gagnante',
            field=models.ForeignKey(help_text='Offre classée Rang 1 après évaluation', on_delete=django.db.models.deletion.PROTECT, related_name='contrat', to='ouverture_offre.offreouverture'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='ouverture_offre.seanceouverture'),
        ),
        migrations.AddField(
            model_name='audittrailcontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='contractualisation.contrat'),
        ),
        migrations.AddField(
            model_name='documentcontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contractualisation.contrat'),
        ),
        migrations.AddField(
            model_name='documentcontrat',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='echeancierpaiement',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeancier', to='contractualisation.contrat'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['statut', '-created_at'], name='contractual_statut_399b74_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['numero_marche'], name='contractual_numero__c1f1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrailcontrat',
            index=models.Index(fields=['contrat', '-timestamp'], name='contractual_contrat_186045_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrailcontrat',
            index=models.Index(fields=['action', '-timestamp'], name='contractual_action_c4eb46_idx'),
        ),
    ]
