# Generated by Django 5.2.10 on 2026-07-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrailcontrat',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('UPLOAD', 'Upload document'), ('DELETE', 'Suppression document'), ('SEND', 'Envoi au prestataire'), ('SIGN', 'Signature'), ('VALIDATE', 'Validation'), ('CANCEL', 'Annulation')], max_length=20),
        ),
    ]
