# Generated by Django 5.2.10 on 2026-07-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0002_add_delete_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'À contractualiser'), ('ATTENTE_SIGNATURE', 'En attente de signature'), ('EXECUTION', 'En exécution'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20),
        ),
    ]
