# Generated by Django 5.2.10 on 2026-08-11 11:08

import apps.contractualisation.models.contrat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=apps.contractualisation.models.contrat._statut_contrat_choices, default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentcontrat',
            name='type_document',
            field=models.CharField(choices=apps.contractualisation.models.contrat._type_document_contrat_choices, default='CONTRAT_SIGNE', max_length=20),
        ),
    ]
