# Generated by Django 5.2.10 on 2026-08-25 11:23

import apps.contractualisation.models.contrat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0003_alter_contrat_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrailcontrat',
            name='action',
            field=models.CharField(choices=apps.contractualisation.models.contrat._action_audit_contrat_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='echeancierpaiement',
            name='statut',
            field=models.CharField(choices=apps.contractualisation.models.contrat._statut_paiement_choices, default='EN_ATTENTE', max_length=20),
        ),
    ]
